In [ ]:
#needs to be executed in terminal
pip install fuzzywuzzy
pip install python-Levenshtein

In [1]:
import re
import pandas as pd
import numpy as np
from pathlib import Path
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

# Functions

In [3]:
#Code snippet: https://programminghistorian.org/en/lessons/generating-an-ordered-data-set-from-an-OCR-text-file

'''
Code ripped from https://www.datacamp.com/community/tutorials/fuzzy-string-python
'''
def lev(seq1, seq2):
    """ levenshtein_ratio_and_distance:
        For all i and j, distance[i,j] will contain the Levenshtein
        distance between the first i characters of seq1 and the
        first j characters of seq2
    """
    # Initialize matrix of zeros
    rows = len(seq1)+1
    cols = len(seq2)+1
    distance = np.zeros((rows,cols),dtype = int)

    # Populate matrix of zeros with the indeces of each character of both strings
    for i in range(1, rows):
        for k in range(1,cols):
            distance[i][0] = i
            distance[0][k] = k

    # Iterate over the matrix to compute the cost of deletions,insertions and/or substitutions    
    for col in range(1, cols):
        for row in range(1, rows):
            if seq1[row-1] == seq2[col-1]:
                cost = 0 # If the characters are the same in the two strings in a given position [i,j] then the cost is 0
            else:
                # In order to align the results with those of the Python Levenshtein package, if we choose to calculate the ratio
                # the cost of a substitution is 2. If we calculate just distance, then the cost of a substitution is 1.
                cost = 1
            distance[row][col] = min(distance[row-1][col] + 1,      # Cost of deletions
                                 distance[row][col-1] + 1,          # Cost of insertions
                                 distance[row-1][col-1] + cost)     # Cost of substitutions

    return distance[row][col]

# Code

## GEG

### Section Tagging

##### Manual changes: 

 
- In file 1873_GEG_New.txt I manually removed additional spaces from line 632 and line 1626.  
- In file 1874_GEG_New.txt I manually removed additional spaces from line 3747 and line 5449 and line 6234.  
- In file 1875_GEG_New.txt I manually removed additional spaces from line 957 and line 5255.  
- In file 1875_GEG_New.txt I manually added a line break in line 6016 after "Verzeichnis ".
- In file 1876_GEG_New.txt I manually removed additional spaces from line 7158.
- In file 1876_GEG_New.txt I manually added a line break in line 8200 after "Verzeichnis ".
- In file 1877_GEG_New.txt I manually removed additional spaces from line 1790.
- In file 1877_GEG_New.txt I manually added a line break in line 5130 after "Verzeichnis ".
- In file 1878_GEG_New.txt I manually removed additional symbols bevor and after the content from line 5052.
- In file 1878_GEG_New.txt I manually added a line break in line 8490 after "Verzeichnis ".
- In file 1879_GEG_New.txt I manually added a line break in line 7390 after "Verzeichnis ".
- In file 1880_GEG_New.txt I manually added a line break in line 6022 after "Verzeichnis ".
- In file 1881_GEG_New.txt I manually added a line break in line 7500 after "Verzeichnis ".
- In file 1882_GEG_New.txt I manually added a line break in line 4971 to move the "Sitzung" in a new line.
- In file 1882_GEG_New.txt I manually added a line break in line 7860 after "Verzeichnis ".
- In file 1882_GEG_New.txt I manually removed additional spaces from line 8424.
- In file 1883_GEG_New.txt I manually added a line break in line 5306 after "Verzeichnis ".
- In file 1884_GEG_New.txt I manually added a line break in line 9822 after "Verzeichnis ".
- In file 1885_GEG_New.txt I manually added a line break in line 10083 after "Verzeichnis ".
- In file 1886_GEG_New.txt I manually added a line break in line 9575 after "Verzeichnis ".
- In file 1887_GEG_New.txt I manually added a line break in line 4721 after "Verzeichnis ".
- In file 1887_GEG_New.txt I manually removed additional spaces from line 5122 and line 5367 and line 5625.
- In file 1888_GEG_New.txt I manually added "Jahresversammlung" and a line break in line 72.
- In file 1888_GEG_New.txt I manually added a line break in line 8039 after "Verzeichnis ".
- In file 1889_GEG_New.txt I manually added a line break in line 5197 after "Verzeichnis ".
- In file 1890_GEG_New.txt I manually added a line break in line 3908 after "Verzeichnis ".
- In file 1891_GEG_New.txt I manually added a line break in line 4752 after "Verzeichnis ".
- In file 1892_GEG_New.txt I manually added a line break in line 3944 after "Verzeichnis ".
- NB: File 1892_GEG_New.txt has missing numbers for the members-list between line 4142 and line 4221.
- In file 1893_GEG_New.txt I manually added a line break in line 4384 after "Verzeichnis ".
- In file 1894_GEG_New.txt I manually added a line break in line 6047 after "Verzeichnis ".
- NB: File 1894_GEG_New.txt has missing numbers for the members-list between line 6180 and line 6212.
- In file 1895_GEG_New.txt I manually added a line break in line 4303 after "Verzeichnis ".
- In file 1896_GEG_New.txt I manually added a line break in line 5780 after "Verzeichnis ".
- In file 1896_GEG_New.txt I manually removed additional spaces from line 6212 and line 6463.
- In file 1897_GEG_New.txt I manually added a line break in line 6221 after "Verzeichnis ".
- In file 1898_GEG_New.txt I manually added a line break in line 4560 after "Verzeichnis ".
- In file 1899_GEG_New.txt I manually added a line break in line 4992 after "Verzeichnis ".
- In file 1900_GEG_New.txt I manually added a line break in line 6014 after "Verzeichnis ".
- NB: File 1900_GEG_New.txt has missing numbers for the members-list between line 6191 and line 6225.
- In file 1901_GEG_New.txt I manually added a line break in line 9401 after "Verzeichnis ".
- In file 1901_GEG_New.txt I manually removed a line break in line 7995 after "Verzeichnis ".
- In file 1902_GEG_New.txt I manually added a line break in line 6192 after "Verzeichnis ".
- In file 1903_GEG_New.txt I manually added a line break in line 100, line 240, line 466, line 534, line 686, and line 785 after "Sitzung".
- In file 1903_GEG_New.txt I manually added a line break in line 1279 after "Verzeichnis ".
- In file 1903_GEG_New.txt I manually removed a line break in line 6357 after "Verzeichnis ".
- In file 1904_GEG_New.txt I manually added a line break in line 224, line 240, line 389, line 446, line 910, line 1087, line 1198, and line 1335 after "Sitzung".
- In file 1904_GEG_New.txt I manually added a line break in line 1578 after "Verzeichnis ".
- NB: File 1904_GEG_New.txt has missing numbers for the members-list between line 1765 and line 1798.
- NB: File 1904_GEG_New.txt has missing numbers for the members-list between line 1845 and line 1878.
- In file 1905_GEG_New.txt I manually added a line break in line 90, line 208, line 270, line 581, line 679, line 966, line 1215, and line 1278 after "Sitzung".
- In file 1905_GEG_New.txt I manually added a line break in line 1470 after "Verzeichnis ".
- In file 1906_GEG_New.txt I manually added a line break in line 68, line 112, line 222, line 339, line 513, line 632, and line 703 after "Sitzung".
- In file 1906_GEG_New.txt I manually added a line break in line 881 after "Verzeichnis ".
- In file 1907_GEG_New.txt I manually added a line break in line 99, line 168, line 209, line 275, line 433, line 537, line 890, line 951, and line 1084 after "Sitzung".
- In file 1907_GEG_New.txt I manually added a line break in line 1386 after "Verzeichnis ".
- In file 1908_GEG_New.txt I manually added a line break in line 97, line 245, line 319, line 449, line 614, line 851, line 1045, and line 1113 after "Sitzung".
- In file 1908_GEG_New.txt I manually added a line break in line 1500 after "Verzeichnis ".
- In file 1909_GEG_New.txt I manually added a line break in line 85, line 486, line 628, line 762, line 898, line 1281, and line 1367 after "Sitzung".
- In file 1909_GEG_New.txt I manually added a line break in line 1651 after "Verzeichnis ".
- In file 1910_GEG_New.txt I manually added a line break in line 93, line 254, line 336, line 389, line 458, line 529, line 579 and line 604 after "Sitzung".
- In file 1910_GEG_New.txt I manually added a line break in line 731 after "Verzeichnis ".
- NB: File 1910_GEG_New.txt has missing numbers for the members-list between line 760 and line 790.
- In file 1911_GEG_New.txt I manually added a line break in line 86, line 226, line 301, line 389, line 520, line 578, and line 639 after "Sitzung".
- In file 1911_GEG_New.txt I manually added a line break in line 3742 and in line 4552 after "Verzeichnis ".
- NB: In file 1911_GEG_New.txt the last "Verzeichnis" is the membership list. 
- In file 1912-1922_GEG_New.txt I manually added a line break in line 3167 after "Sitzung" and replaced "Außerordentliche Sitzung" with "XXX. Monatssitzung"
- In file 1912-1922_GEG_New.txt I manually added a line break in line 72, line 349, line 392, line 3249, line 3364, line 4247, line 4267, line 4378, line 4585, line 4777, line 4904, line 5072, line 5187, and line 5294 after "Monatssitzung".
- In file 1912-1922_GEG_New.txt I manually added a line break in line 3742 and in line 8407 after "Verzeichnis ".
- NB: In file 1912-1922_GEG_New.txt the membership list does have a completely different layout. 

- NB: !!! file 1912-1922_GEG_Ano.txt not all original lines were transfered !!!

##### Code

In [92]:
#I read the file into a list
filename = 'Sources/GEG/1912-1922_GEG_New.txt'
with open(filename, 'r') as fp:
    text = fp.readlines()
    

In [93]:
#I check whether all the sections I want to tag are being detected. 
#If I do notice missing sections I have to check the file manually and adapt the lines if needed.

for num, line in enumerate(text, 1):
    
    yearlymeet_lev_score = lev(line,'Jahresversammlung \n')                            
    section_lev_score = lev(line, '750. Monatssitzung \n')                                    #I adjust this as best I can to what the ideal outcome would be
    list_lev_score = lev(line, 'Verzeichnis \n')
    
    if yearlymeet_lev_score <= 5:                                                       #I tweak the score until it fits best
        print(f"YOccurence: {line}; Score: {yearlymeet_lev_score}; in Line: {num}")
    elif section_lev_score <= 5:                                                        #I tweak the score until it fits best
        print(f"SOccurence: {line}; Score: {section_lev_score}; in Line: {num}")
    elif list_lev_score <= 5:                                                           #I tweak the score until it fits best
        print(f"LOccurence: {line}; Score: {list_lev_score}; in Line: {num}")
    

YOccurence: Jahresversammlung 
; Score: 0; in Line: 72
SOccurence: 755. Monatssitzung 
; Score: 1; in Line: 349
SOccurence: 756. Monatssitzung 
; Score: 1; in Line: 392
YOccurence: Jahresversammlung 
; Score: 0; in Line: 500
SOccurence: XXX. Monatssitzung 
; Score: 3; in Line: 3167
SOccurence: 757. Monatssitzung 
; Score: 1; in Line: 3249
SOccurence: 758. Monatssitzung 
; Score: 1; in Line: 3364
YOccurence: Jahresversammlung 
; Score: 0; in Line: 4247
SOccurence: 760. Monatssitzung 
; Score: 1; in Line: 4267
SOccurence: 761. Monatssitzung 
; Score: 2; in Line: 4378
SOccurence: 762. Monatssitzung 
; Score: 2; in Line: 4585
SOccurence: 763. Monatssitzung 
; Score: 2; in Line: 4777
SOccurence: 764. Monatssitzung 
; Score: 2; in Line: 4904
SOccurence: 765. Monatssitzung 
; Score: 2; in Line: 5072
SOccurence: 766. Monatssitzung 
; Score: 2; in Line: 5187
SOccurence: 767. Monatssitzung 
; Score: 2; in Line: 5294
LOccurence: Verzeichnis 
; Score: 0; in Line: 8407


In [94]:
#I create a new list with the lines that mark sections being tagged.
#I have to adjust the changes made above

new_text = []

for num, line in enumerate(text, 0):
    
    yearlymeet_lev_score = lev(line,'Jahresversammlung \n')                            
    section_lev_score = lev(line, '750. Monatssitzung \n')                     #I adjust this as best I can to what the ideal outcome would be
    list_lev_score = lev(line, 'Verzeichnis \n')
    
    if yearlymeet_lev_score <= 5:
        ano_line = f"<section type='yearlymeet'> {line}"                 #I open the section tag in the line I detected
        new_text.append(ano_line)
         
    elif section_lev_score <= 5:
        new_text.append("</section> \n")                                 #I close the section tag with an additional line before the new section starts 
        ano_line = f"<section type='monthlymeet'> {line}"
        new_text.append(ano_line)
        
    elif list_lev_score <= 5:
        new_text.append("</section> \n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)
        
    else:
        new_text.append(line)
        
new_text.append("</section> \n")                                         #I close the very last section 
        

In [95]:
new_text[330:360]

['*) Der zum Schluss der Sitzung verlesene Jahresbericht für das \n',
 'Jahr 1911 ist in den S.-B. des Jahres auf S. 115 ff. veröffentlicht. \n',
 '8 \n',
 'schwere verzierte silberne Armringe von schöner Arbeit, ein \n',
 'grosser Ring aus dickem gewundenen Golddraht und 11 grosse \n',
 'silberne Ringe, stabrund mit eingestempelten Verzierungen, \n',
 'facettiert oder gewunden, wie sie gewöhnlich als Halsringe ange\xad\n',
 'sprochen werden, aber im vorliegenden Falle eher als Kopf\xad\n',
 'schmuck zu deuten sind. \n',
 'Ein derartiger Fund ist bisher in unseren Provinzen nicht \n',
 'gemacht worden. Nur eine Armbrustfibel von derselben Aus\xad\n',
 'stattung hat sich bei Riga (Plawnekaln) gefunden, doch ähnliche \n',
 'Bronzefibeln bieten Ostpreussen und Finnland. Es handelt sich \n',
 'bei den neben dem Stein gefundenen Sachen nicht um eine Toten\xad\n',
 'beigabe, auch nicht um einen vergrabnen Schatz, da die Gegen\xad\n',
 'stände gleich gemustert sind, meist ganz neu, ohne Spure

In [96]:
#I write the new annotated list into a .txt file 

out_filename = 'Output/GEG/1912-1922_GEG_Ano.txt'                            #Look out for the right year!!

filepath = Path(out_filename)                             
filepath.parent.mkdir(parents=True, exist_ok=True)                       #creates the folders if they don't exist yet

with open(out_filename, 'x') as fp:
    fp.write("".join(str(item) for item in new_text))

### Isolating and annotating membership list 

##### Manual Changes:


- In file 1876_GEG_Members_Ano.txt there is no second level homeland/abroad distinction for OM only an in_hometown/outside_hometown distinction. 
- In file 1877_GEG_Members_Ano.txt there is no second level homeland/abroad distinction for OM only an outside_hometown marker. 
- In file 1877_GEG_Members_Ano.txt I manually adapt the wrongly formated persons in line 9 (person 5).
- NB: In file 1878_GEG_Members_Ano.txt there are a few persons that were not detected correctly and now share a line with the person before.
- In file 1878_GEG_Members_Ano.txt I manually adapt the wrongly formated persons in line 36 (person 4), line 103 (person 71), line 143 (person 109), and in line 203 (person 26).
- In file 1878_GEG_Members_Ano.txt I manually remove not detected page numbers from line 9, line 66, and line 192. 
- In file 1880_GEG_Members_Ano.txt I remove a wrongly set line break in line 233.
- In file 1881_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 136 (person 101), line 173 (person 138), line 200 (person 22), line 236 (person 58).
- In file 1882_GEG_Members_Ano.txt I manually remove not detected page numbers from line 95, line 119, and line 139.
- In file 1882_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 153 (person 117).
- In file 1883_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 13 (person 9), line 15 (person 11), line 27 (person 22), line 263 (person 69).
- In file 1884_GEG_Members_Ano.txt I manually remove not detected page numbers from line 59, and line 205.
- In file 1884_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 91 (person 58).
- In file 1885_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 9 (person 5), line 12 (person 8), line 129 (person 93-116), line 209 (person 24).
- In file 1886_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 40.
- In file 1887_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 41 (person 35),
- In file 1887_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 58.
- In file 1887_GEG_Members_Ano.txt I manually remove not detected page numbers from line 202.
- In file 1888_GEG_Ano.txt I manually correct the HM homeland label, which was falsely printed as "Im Auslande" in line 8052.
- In file 1888_GEG_Ano.txt I manually correct the CM homeland label, because it would only have been detected with a fuzz.ratio that also detects the abroad tag as a homeland tag in line 8337. 
- In file 1888_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 60.
- In file 1888_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 88 (person 42-71).
- In file 1888_GEG_Members_Ano.txt I manually remove not detected page numbers from line 252, and line 277.
- In file 1889_GEG_Ano.txt I manually add I line break before "Ehrenmitglieder" in line 5210. 
- In file 1889_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 64.
- In file 1889_GEG_Members_Ano.txt I manually remove not detected page numbers from line 206.
- In file 1889_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 254 (person 3-27).
- NB: In file 1890_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM. The code needs to be slightly adjusted.
- In file 1890_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 146.
- In file 1890_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 198 (person 73-96), in line 286 (person 161-162), and in line 325 (person 202).
- NB: In file 1891_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM.
- In file 1891_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 82 (person 43-44), in line 86 (person 45-61), and in line 284 (person 163).
- In file 1891_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 126.
- NB: In file 1892_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM.
- In file 1892_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 61 (person 22-43), in line 85 (person 43-45), in line 134 (person 16-43), in line 164 (person 46-76), and in line 311 (person 191).
- In file 1892_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 134.
- In file 1892_GEG_Members_Ano.txt I manually remove not detected page numbers from line 230.
- NB: In file 1893_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM.
- In file 1893_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 10 (person 6), and in line 167 (person 50-83).
- In file 1893_GEG_Members_Ano.txt I manually remove not detected page numbers from line 36, line 88.
- In file 1893_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 137.
- NB: In file 1894_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM.
- In file 1894_GEG_Ano.txt I manually correct the CM homeland label, because it would only have been detected with a fuzz.ratio that also detects the abroad tag as a homeland tag in line 6121.
- In file 1894_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 67 (person 27), in line 86 (person 44-61), in line 157 (person 40-99), in line 241 (person 122-141), in line 264 (person 145-146),in line 275 (person 156) in line 280 (person 161), and in line 282 (person 163).
- In file 1894_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 129.
- NB: In file 1895_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM.
- In file 1895_GEG_Ano.txt I manually correct the HM abroad tag, because it was too faulty to be detected in line 4359.
- In file 1895_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 9 (person 5), in line 50 (person 10), and in line 53 (person 13). 
- In file 1895_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 128.
- NB: In file 1896_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM. Also changed marker for in/outside town, code needs to be adjusted. 
- In file 1896_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 136.
- NB: In file 1897_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM. Also changed marker for in/outside town.
- In file 1897_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 133.
- In file 1897_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 133 (person 26-54), in line 215 (person 106).
- NB: In file 1898_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM. Also changed marker for in/outside town.
- In file 1898_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 54 (person 17).
- In file 1898_GEG_Members_Ano.txt I manually remove not detected page numbers from line 62.
- In file 1898_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 131.
- NB: In file 1899_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM. Also changed marker for in/outside town.
- In file 1899_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 96 (person 60), and in line 103 (person 2).
- In file 1899_GEG_Members_Ano.txt I manually remove not detected page numbers from line 61.
- In file 1899_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 125.
- NB: In file 1900_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM. Also changed marker for in/outside town.
- In file 1900_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 101.
- In file 1900_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 101 (person 4-33), in line 176 (person 77), in line 190 (person 91) in line 192 (person 93), and in line 199 (person 100).
- NB: In file 1901_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM. Also changed marker for in/outside town.
- In file 1901_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 64 (person 31), in line 129 (person 33-64), and in line 187 (person 89-131).
- In file 1901_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 100.
- NB: In file 1902_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM. Also changed marker for in/outside town.
- In file 1902_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 52 (person 20).
- In file 1902_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 122.
- NB: In file 1903_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM. Also changed marker for in/outside town.
- In file 1903_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 119.
- In file 1903_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 142 (person 48).
- NB: In file 1904_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM. Also changed marker for in/outside town.
- In file 1904_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 120.
- In file 1904_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 158 (person 64-97), and in line 230 (person 134-162).
- NB: In file 1905_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM. Also changed marker for in/outside town.
- In file 1905_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 92 (person 1-27), in line 196 (person 103-134), and in line 229 (person 136-165).
- In file 1904_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 120.
- NB: In file 1906_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM.
- In file 1906_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 8 (person 4), in line 91 (person 1-27), and in line 119 (person 28-94).
- In file 1906_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 119.
- NB: In file 1907_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM.
- In file 1907_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 110.
- In file 1907_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 115 (person 31), and in line 146 (person 62-98).
- NB: In file 1908_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM.
- In file 1908_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 109.
- NB: In file 1909_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM.
- In file 1909_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 8 (person 4), and in line 206 (person 124).
- In file 1909_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 112.
- NB: In file 1910_GEG_Ano.txt the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM.
- In file 1910_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 25 (person 1-20), and in line 112 (person 32-68).
- In file 1909_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 112.
- NB: In file 1911_GEG_Ano.txt the numbers end with a "." instead of a ")" the code needs to be adjusted accordingly. Also, the sequence of 1st level membership status information is switched being HM, CM, OM not HM, OM, CM. 
- In file 1911_GEG_Members_Ano.txt I manually corrected line 27 and line 262.
- In file 1911_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 81 and line 117.
- NB: In file 1912-1922_GEG_Ano.txt I manually insert a closing section tag in line 8536 and an opening section tag (without type) in line 8537. Due to the vastly different layout of this issue the end of the membership list was not picked up automatically. I also manually add the line breaks for the structural elements and correct them if necessary. 
- In file 1921_GEG_Members_Ano.txt I manually adapt the wrongly formated person in line 5 (person 1), and in line 20 (person 1).
- In file 1921_GEG_Members_Ano.txt I manually remove the note regarding the paid membership fees in line 62.
- In file 1921_GEG_Members_Ano.txt I manually correct line 40, and line 46.


##### Code

In [180]:
#I read the file into a list
filename = 'Output/GEG/1912-1922_GEG_Ano.txt'
with open(filename, 'r') as fp:
    text = fp.readlines()
    

In [181]:
#I look for the section markers and write them in lists

sections_s = []
sections_e = []

for num, line in enumerate(text, 0):
    if line.startswith("<section type='list'>"):                           #Only section beginnings with marker "list".
        sections_s.append(num)
        
for num, line in enumerate(text, 1):        
    if line == "</section> \n":                                            #All section endings are the same.
        sections_e.append(num)
        
print(sections_s)
print(sections_e)


[8420]
[349, 393, 3169, 3252, 3368, 4272, 4384, 4592, 4785, 4913, 5082, 5198, 5306, 8420, 8547, 18695]


In [182]:
#I check which of the list sections is the membership list and create a list only with this section
members_text = text[sections_s[0]:sections_e[-2]]
members_text

["<section type='list'> Verzeichnis \n",
 'der Mitglieder zum 10. Januar 1921. \n',
 'Ehrenmitglieder: \n',
 'Im Inlander  \n',
 '1 )  K u r a t o r  P r o f e s s o r  \n',
 'P. Põld, 1920. — \n',
 'Im Auslande: \n',
 '2) Dr. Hermann v. В r u i \n',
 'ningk in Riga, 1887; 3) Dr. Adalbert Bezzenberger ProL \n',
 'in Königsberg, 1894; 4) Stadtarchivar Mag. Arnold Peuereisen \n',
 'in Riga, 1920; 5) Friedrich v. Keussler in Greifswald, 1920; \n',
 '6) Reichsantiquar Prof. Oskar Montelius in Stockholm, 1920; \n',
 '7) Prof. Dr. Emil Setälä in Helsingfors, 1920; 8) Wilhelm \n',
 'Thomsen in Kopenhagen, 1887; 9) Gräfin Praskowja Sserge-\n',
 'jewna Uwarow in Moskau, 1887. \n',
 'Korrespondierende Mitglieder :  \n',
 'Im Inlande:  \n',
 '1 )  P r o f .  \n',
 'Dr. Eduard Berendts in Dorpat, 1899 ; 2) Prof. Dr. Alexander \n',
 'Rosenberg in Dorpat, 1896; 3) Leo v. Si ver s Alt-Kusthof, \n',
 '1902; 4) Alexander v. S i v e r s Rappin, 1920; 5) Oberlehrer \n',
 'Arthur Spreckelsen in Reval, 190

In [183]:
#To create and better visualize the annotation structure I first created a template manually. 

#First round annotating the membership list
#I again use XML inspired tags to mark the structuring elements of the list.
#This is the first level of information including the status of their membership: honorable, ordinary or corresponding.
#Depending on the quality of the OCR these reference words need to be adapted.

members_ano_1 = []
for line in members_text: 
    hon_mem = fuzz.ratio("Ehrenmitglieder", line)                                  #Fuzz works with the lev function, but makes it way faster.
    ord_mem = fuzz.ratio("Ordentliche Mitglieder", line)                           #I had difficulties installing fuzzywuzzy in jupyter labs and therefore didn't use it earlier. 
    cor_mem = fuzz.ratio("Correspondierende Mitglieder", line)
    
    if hon_mem >= 90:
        members_ano_1.append("<members>")                                          #I open members section
        members_ano_1.append(f"<honorable_members> {line}")                        #I open honorable members section
        print("HM detected")
    
    elif ord_mem >= 80:
        #members_ano_1.append("</honorable_members>")                               #I close honorable members section
        members_ano_1.append("</corresponding_members>")
        members_ano_1.append(f"<ordinary_members> {line}")                         #I open ordinary members section
        print("OM detected")
        
    elif cor_mem >=80:
        #members_ano_1.append("</ordinary_members>")                               #I close ordinary members section
        members_ano_1.append("</honorable_members>")
        members_ano_1.append(f"<corresponding_members> {line}")                    #I open corresponding members section
        print("CM detected")
        
    elif line == "</section> \n":
        #members_ano_1.append("</corresponding_members>")                           #I close corresponding members section
        members_ano_1.append("</ordinary_members>")
        members_ano_1.append("</members>")                                         #I close members section
        members_ano_1.append(line)
        print("Section tag detected")
    
    else:                                                                          #Don't forget to also append the rest of the original list
        members_ano_1.append(line)
        
members_ano_1

HM detected
CM detected
OM detected
Section tag detected


["<section type='list'> Verzeichnis \n",
 'der Mitglieder zum 10. Januar 1921. \n',
 '<members>',
 '<honorable_members> Ehrenmitglieder: \n',
 'Im Inlander  \n',
 '1 )  K u r a t o r  P r o f e s s o r  \n',
 'P. Põld, 1920. — \n',
 'Im Auslande: \n',
 '2) Dr. Hermann v. В r u i \n',
 'ningk in Riga, 1887; 3) Dr. Adalbert Bezzenberger ProL \n',
 'in Königsberg, 1894; 4) Stadtarchivar Mag. Arnold Peuereisen \n',
 'in Riga, 1920; 5) Friedrich v. Keussler in Greifswald, 1920; \n',
 '6) Reichsantiquar Prof. Oskar Montelius in Stockholm, 1920; \n',
 '7) Prof. Dr. Emil Setälä in Helsingfors, 1920; 8) Wilhelm \n',
 'Thomsen in Kopenhagen, 1887; 9) Gräfin Praskowja Sserge-\n',
 'jewna Uwarow in Moskau, 1887. \n',
 '</honorable_members>',
 '<corresponding_members> Korrespondierende Mitglieder :  \n',
 'Im Inlande:  \n',
 '1 )  P r o f .  \n',
 'Dr. Eduard Berendts in Dorpat, 1899 ; 2) Prof. Dr. Alexander \n',
 'Rosenberg in Dorpat, 1896; 3) Leo v. Si ver s Alt-Kusthof, \n',
 '1902; 4) Alexander

In [184]:
#I determine where the first level structural elements start and end, 
#because I want the lower levels to reference the parent in order to avoid a duplicate in a marker opener.

for num, line in enumerate(members_ano_1, 0):
    if line.startswith("<honorable_members>"):                    #The opening marker gives the number for the starting point of the iteration of the list.
        start_hm = num
    if line == "</honorable_members>":                            #The closing marker gives the number for the end point of the iteration of the list.
        end_hm = num +1                                           #I add 1 because I want the closing line itself also included in the iterated section.            
        
for num, line in enumerate(members_ano_1, 0):
    if line.startswith("<ordinary_members>"):
        start_om = num
    if line == "</ordinary_members>":
        end_om = num +1

for num, line in enumerate(members_ano_1, 0):
    if line.startswith("<corresponding_members>"):
        start_cm = num
    if line == "</corresponding_members>":
        end_cm = num +1        

#members_ano_1[start_om:end_om]

In [185]:
#Second round annotating the membership list
#This is the second level of information including the location of the member as inside or outside of the Russian Empire.
#Since this distinction is made for each of the first level structural elements I want to uniquely describe the opening markers.

members_ano_2 = []

for num, line in enumerate(members_ano_1, 0):
    if num in range(start_hm, end_hm):                                   #I only go through the range of the honorable members section.

        home_mem = fuzz.ratio("Im Inlande. ", line)                 
        abroad_mem = fuzz.ratio("Im Auslande. ", line)

        if home_mem >= 80:
            members_ano_2.append(f"<homeland parent='HM'> {line}")       #I open the homeland section for honorable members
            print("HM homeland detected")

        elif abroad_mem >= 70:
            members_ano_2.append("</homeland>")                          #I close the homeland section 
            members_ano_2.append(f"<abroad parent='HM'> {line}")         #I open the abroad section for honorable members
            print("HM abroad detected")

        elif line == "</honorable_members>":
            members_ano_2.append("</abroad>")                            #I close the abroad section 
            members_ano_2.append(line)
            print("HM tag detected")
            
        else:
            members_ano_2.append(line)                                   #Don't forget to append the lines in between. 
    
    elif num in range(start_om, end_om):                                 #I only go through the range of the ordinary members section.

        #home_mem = fuzz.ratio("Im Inlande. ", line)
        #abroad_mem = fuzz.ratio("Im Auslande. ", line)
        in_mem = fuzz.ratio("I. In Dorpat. ", line)
        out_mem = fuzz.ratio("II. Außerhalb Dorpats. ", line)

        if in_mem >= 70:
            members_ano_2.append(f"<in_hometown> {line}")                 #I open the in hometown section
            print("OM In detected")

        elif out_mem >= 65:
            members_ano_2.append("</in_hometown>")                        #I close the in hometown section 
            members_ano_2.append(f"<outside_hometown> {line}")
            print("OM Out detected")

        #if home_mem >= 80:
            #members_ano_2.append(f"<homeland parent='OM'> {line}")       #I open the homeland section for the ordinary members

        #elif abroad_mem >= 80:
           # members_ano_2.append("</homeland>")                          #I close the homeland section 
            #members_ano_2.append(f"<abroad parent='OM'> {line}")         #I open the abroad section for the ordinary members

        elif line == "</ordinary_members>":     
            #members_ano_2.append("</abroad>")                             #I close the abroad section
            members_ano_2.append("</outside_hometown>")                   #I close the outside hometown section
            members_ano_2.append(line)
            print("OM tag detected")
            
        else:
            members_ano_2.append(line)
    
    elif num in range(start_cm, end_cm):                                 #I only go through the range of the corresponding members section.

        home_mem = fuzz.ratio("Im Inlande. ", line)
        abroad_mem = fuzz.ratio("Im Auslande. ", line)

        if home_mem >= 80:
            members_ano_2.append(f"<homeland parent='CM'> {line}")       #I open the homeland section for the corresponding members
            print("CM homeland detected")

        elif abroad_mem >= 80:
            members_ano_2.append("</homeland>")                          #I close the homeland section 
            members_ano_2.append(f"<abroad parent='CM'> {line}")         #I open the abroad section for the corresponding members
            print("CM abroad detected")

        elif line == "</corresponding_members>":
            members_ano_2.append("</abroad>")                            #I close the abroad section 
            members_ano_2.append(line)
            print("CM tag detected")
            
        else:
            members_ano_2.append(line)
    
    
    else:
        members_ano_2.append(line)                                       #Don't forget to also append the lines outside of the sections.

members_ano_2

HM homeland detected
HM abroad detected
HM tag detected
CM homeland detected
CM abroad detected
CM tag detected
OM In detected
OM Out detected
OM tag detected


["<section type='list'> Verzeichnis \n",
 'der Mitglieder zum 10. Januar 1921. \n',
 '<members>',
 '<honorable_members> Ehrenmitglieder: \n',
 "<homeland parent='HM'> Im Inlander  \n",
 '1 )  K u r a t o r  P r o f e s s o r  \n',
 'P. Põld, 1920. — \n',
 '</homeland>',
 "<abroad parent='HM'> Im Auslande: \n",
 '2) Dr. Hermann v. В r u i \n',
 'ningk in Riga, 1887; 3) Dr. Adalbert Bezzenberger ProL \n',
 'in Königsberg, 1894; 4) Stadtarchivar Mag. Arnold Peuereisen \n',
 'in Riga, 1920; 5) Friedrich v. Keussler in Greifswald, 1920; \n',
 '6) Reichsantiquar Prof. Oskar Montelius in Stockholm, 1920; \n',
 '7) Prof. Dr. Emil Setälä in Helsingfors, 1920; 8) Wilhelm \n',
 'Thomsen in Kopenhagen, 1887; 9) Gräfin Praskowja Sserge-\n',
 'jewna Uwarow in Moskau, 1887. \n',
 '</abroad>',
 '</honorable_members>',
 '<corresponding_members> Korrespondierende Mitglieder :  \n',
 "<homeland parent='CM'> Im Inlande:  \n",
 '1 )  P r o f .  \n',
 'Dr. Eduard Berendts in Dorpat, 1899 ; 2) Prof. Dr. Alex

In [ ]:
#Skip if no 3rd Level of Membership Status

#I get the start and end point of the homeland section of ordinary members

for num, line in enumerate(members_ano_2, 0):
    if line.startswith("<homeland parent='OM'>"):
        start_hl = num
    if line.startswith("<abroad parent='OM'>"):           #Since the closing section is the same for all membership status section I have to use the next best unique identifier
        end_hl = num                                      #Now with out the added 1 so I only get the list until the closing mark 
        
        
#members_ano_2[start_hl:end_hl]

In [ ]:
#Skip if no 3rd Level of Membership Status

#Third round annotating the membership list. 
#Only the homeland section for the ordinary members further destinguishes between people living within Dorpat/Riga or outside of it. 


members_ano_3 = []

for num, line in enumerate(members_ano_2, 0):
    if num in range(start_hl, end_hl):                                    #Only the range of homeland section for ordinary members

        in_mem = fuzz.ratio("I. In Dorpat. ", line)
        out_mem = fuzz.ratio("II. Außerhalb Dorpat. ", line)

        if in_mem >= 90:
            members_ano_3.append(f"<in_hometown> {line}")                 #I open the in hometown section 

        elif out_mem >= 90:
            members_ano_3.append("</in_hometown>")                        #I close the in hometown section 
            members_ano_3.append(f"<outside_hometown> {line}")            #I open the outside hometown section 

        elif line == "</homeland>":
            members_ano_3.append("</outside_hometown>")                   #I close the outside hometown section 
            members_ano_3.append(line)
            
        else:
            members_ano_3.append(line)
    
    else:
        members_ano_3.append(line)
        
members_ano_3

In [186]:
#First step of the cleaning process of the membership list
#Adjust Ano numbers in case third level structure was skipped

members_ano_3 = []

for line in members_ano_2:
    if line.startswith("— "):                      #I remove the page number markers 
        members_ano_2.remove(line)

for line in members_ano_2:
    new_line = re.sub("\n", "", line)             #I remove the line breaks to reconnect information about one person that is split in two lines.
    members_ano_3.append(new_line)

        
#members_ano_3

In [189]:
#Second step of the cleaning process of the membership list
#NB! This is only possible if all members have a clear marker at the beginning --> Some files have OCR errors here. 

members_ano_4 = []

for line in members_ano_3:
    if line.startswith("<"):
        new_line = re.sub(r"<", r"\n<", line)                 #I insert a line break before each marker
        members_ano_4.append(new_line)
    else:
        new_line = re.sub(r"(\S{1,3})\)", r"\n\1)", line)      #I insert a number before each number signifying a person ( I remove the ^ denoting the beginning of the line only for members list 1921.
        members_ano_4.append(new_line)
        
#members_ano_4

In [190]:
out_filename = 'Output/GEG/1921_GEG_Members_Ano.txt'                #Look out for the right year!!

filepath = Path(out_filename)                             
filepath.parent.mkdir(parents=True, exist_ok=True)                  #creates the folders if they don't exist yet

with open(out_filename, 'x') as fp:
    fp.write("".join(str(item) for item in members_ano_4))          #By joining the list elements without any symbol the 
                                                                    #line breaks will be at the end of each line the next time I read the document in 

### Extracting information into a df and .csv

In [385]:
#I read the file into a list
year = "1921"
society = "GEG"

filename = f'Output/{society}/{year}_{society}_Members_Ano.txt'
with open(filename, 'r') as fp:
    text = fp.readlines()

In [386]:
#I figure out the start and endpoints of each of the section so I can later use these to ascribe membership status information in each row

#Honorable Members 
for num, line in enumerate(text, 0):
    if line.startswith("<honorable_members>"):                    #The opening marker gives the number for the starting point of the iteration of the list.
        start_hm = num +1                                         #+1 to start without the structural tag of this section
        #print(f"{start_hm}: {line}")
    if line == "</honorable_members>\n":                          #The closing marker gives the number for the end point of the iteration of the list.
        end_hm = num                                                          
        #print(f"{end_hm}: {line}")
        
#Ordinary Members       
for num, line in enumerate(text, 0):
    if line.startswith("<ordinary_members>"):
        start_om = num +1
        #print(f"{start_om}: {line}")
    if line == "</ordinary_members>\n":
        end_om = num
        #print(f"{end_om}: {line}")

#Corresponding Members
for num, line in enumerate(text, 0):
    if line.startswith("<corresponding_members>"):
        start_cm = num +1
        #print(f"{start_cm}: {line}")
    if line == "</corresponding_members>\n":
        end_cm = num    
        #print(f"{end_cm}: {line}")

In [387]:
#HM Homeland and Abroad
for num, line in enumerate(text, 0):
    if num in range(start_hm, end_hm):
        if line.startswith("<homeland parent='HM'>"):
            start_hm_hl = num +1
        if line == "</homeland>\n":
            end_hm_hl = num
            
    if num in range(start_hm, end_hm):
        if line.startswith("<abroad parent='HM'>"):
            start_hm_ab = num +1
        if line == "</abroad>\n":
            end_hm_ab = num

#OM Homeland and Abroad
for num, line in enumerate(text, 0):
    if num in range(start_om, end_om):
        if line.startswith("<homeland parent='OM'>"):
            start_om_hl = num +1
        if line == "</homeland>\n":
            end_om_hl = num
    
    if num in range(start_om, end_om):
        if line.startswith("<abroad parent='OM'>"):
            start_om_ab = num +1
        if line == "</abroad>\n":
            end_om_ab = num
            
#CM Homeland and Abroad            
for num, line in enumerate(text, 0):
    if num in range(start_cm, end_cm):
        if line.startswith("<homeland parent='CM'>"):
            start_cm_hl = num +1  
        if line == "</homeland>\n":
            end_cm_hl = num
        
    if num in range(start_cm, end_cm):
        if line.startswith("<abroad parent='CM'>"):
            start_cm_ab = num +1
        if line == "</abroad>\n":
            end_cm_ab = num
            
#In Hometown            
for num, line in enumerate(text, 0):
    if line.startswith("<in_hometown>"):
        start_om_in = num +1
    if line == "</in_hometown>\n":
        end_om_in = num

#Outside Hometown
for num, line in enumerate(text, 0):
    if line.startswith("<outside_hometown>"):
        start_om_out = num +1
    if line == "</outside_hometown>\n":
        end_om_out = num        
        
        

In [388]:
#I create an empty data frame to which I will add the individual rows of members
df_main = pd.DataFrame()                                                                                         #Without this it gives me an error that df is not defined in index section
df_main = pd.DataFrame(index = [len(df_main.values)],                                                             #index should count up from 1 to the number of values currently in df
                  columns = ['YEAR', 'SOCIETY', '1L_MS', '2L_MS', '3L_MS', 'NO_MS', 'LINE']) 
df_main

YEAR SOCIETY 1L_MS 2L_MS 3L_MS NO_MS LINE
0  NaN     NaN   NaN   NaN   NaN   NaN  NaN

In [389]:
#I go through each file by each section and create a df for each person 
#Splitting a line by its number spearating it from the sole "text" section 
#The df of a row includes "YEAR", "SOCIETY", "1L_MS", "2L_MS" ("3L_MS"), "NO_MS, "LINE"
#I concat the main df with the row df to add the member 

for num, line in enumerate(text,0):
    
    #Honorable Members
    if num in range(start_hm, end_hm):
        if num in range(start_hm_hl, end_hm_hl):
            row = line.split(")", 1)                          #maxsplits set to 1 to only separate the line after the initial ")" and not further
            
            df_row = pd.DataFrame({"YEAR": year, "SOCIETY": society, "1L_MS": "HM", "2L_MS": "HL", "NO_MS": row[0], "LINE": row[1]},
                                  index = [len(df_main.values)],                                        
                                  columns = ['YEAR', 'SOCIETY', '1L_MS', '2L_MS', 'NO_MS', 'LINE'])
            
            df_main = pd.concat([df_main, df_row])
            
        if num in range(start_hm_ab, end_hm_ab): 
            
            row = line.split(")",1)
            
            df_row = pd.DataFrame({"YEAR": year, "SOCIETY": society, "1L_MS": "HM", "2L_MS": "AB", "NO_MS": row[0], "LINE": row[1]},
                                  index = [len(df_main.values)],                                        
                                  columns = ['YEAR', 'SOCIETY', '1L_MS', '2L_MS', 'NO_MS', 'LINE'])
            
            df_main = pd.concat([df_main, df_row])
        
    #Ordinary Members
    if num in range(start_om, end_om):
        #if num in range(start_om_hl, end_om_hl):
        if num in range (start_om_in, end_om_in):
            row = line.split(")",1)
            
            df_row = pd.DataFrame({"YEAR": year, "SOCIETY": society, "1L_MS": "OM", "2L_MS": "HL", "3L_MS": "IN", "NO_MS": row[0], "LINE": row[1]},
                                  index = [len(df_main.values)],                                        
                                  columns = ['YEAR', 'SOCIETY', '1L_MS', '2L_MS', '3L_MS', 'NO_MS', 'LINE'])
            
            df_main = pd.concat([df_main, df_row])
                
        if num in range (start_om_out, end_om_out):
                row = line.split(")",1)
            
                df_row = pd.DataFrame({"YEAR": year, "SOCIETY": society, "1L_MS": "OM", "3L_MS": "OUT", "NO_MS": row[0], "LINE": row[1]},
                                  index = [len(df_main.values)],                                        
                                  columns = ['YEAR', 'SOCIETY', '1L_MS', '3L_MS', 'NO_MS', 'LINE'])
            
                df_main = pd.concat([df_main, df_row])
            
            #if num in range(start_om_ab, end_om_ab): 
            
                #row = line.split(")",1)
            
                #df_row = pd.DataFrame({"YEAR": year, "SOCIETY": society, "1L_MS": "OM", "2L_MS": "AB", "NO_MS": row[0], "LINE": row[1]},
                                  #index = [len(df_main.values)],                                        
                                  #columns = ['YEAR', 'SOCIETY', '1L_MS', '2L_MS', 'NO_MS', 'LINE'])
            
                #df_main = pd.concat([df_main, df_row])  

    #Corresponding Members
    if num in range(start_cm, end_cm):
        if num in range(start_cm_hl, end_cm_hl):
            row = line.split(")",1)
            
            df_row = pd.DataFrame({"YEAR": year, "SOCIETY": society, "1L_MS": "CM", "2L_MS": "HL", "NO_MS": row[0], "LINE": row[1]},
                                  index = [len(df_main.values)],                                        
                                  columns = ['YEAR', 'SOCIETY', '1L_MS', '2L_MS', 'NO_MS', 'LINE'])
            
            df_main = pd.concat([df_main, df_row])
            
        if num in range(start_cm_ab, end_cm_ab): 
            
            row = line.split(")",1)
            
            df_row = pd.DataFrame({"YEAR": year, "SOCIETY": society, "1L_MS": "CM", "2L_MS": "AB", "NO_MS": row[0], "LINE": row[1]},
                                  index = [len(df_main.values)],                                        
                                  columns = ['YEAR', 'SOCIETY', '1L_MS', '2L_MS', 'NO_MS', 'LINE'])
            
            df_main = pd.concat([df_main, df_row])
            
            

In [390]:
pd.options.display.max_rows = 999
df_main

YEAR SOCIETY 1L_MS 2L_MS 3L_MS NO_MS  \
0     NaN     NaN   NaN   NaN   NaN   NaN   
1    1921     GEG    HM    HL   NaN     1   
2    1921     GEG    HM    AB   NaN     2   
3    1921     GEG    HM    AB   NaN     3   
4    1921     GEG    HM    AB   NaN     4   
5    1921     GEG    HM    AB   NaN     5   
6    1921     GEG    HM    AB   NaN     6   
7    1921     GEG    HM    AB   NaN     7   
8    1921     GEG    HM    AB   NaN     8   
9    1921     GEG    HM    AB   NaN     9   
10   1921     GEG    CM    HL   NaN     1   
11   1921     GEG    CM    HL   NaN     2   
12   1921     GEG    CM    HL   NaN     3   
13   1921     GEG    CM    HL   NaN     4   
14   1921     GEG    CM    HL   NaN     5   
15   1921     GEG    CM    HL   NaN     6   
16   1921     GEG    CM    AB   NaN     7   
17   1921     GEG    CM    AB   NaN     8   
18   1921     GEG    CM    AB   NaN     9   
19   1921     GEG    CM    AB   NaN    10   
20   1921     GEG    CM    AB   NaN    11   
21   1921     GEG    CM    AB   NaN    12   
22   1921     GEG    CM    AB   NaN    13   
23   1921     GEG    CM    AB   NaN    14   
24   1921     GEG    CM    AB   NaN    15   
25   1921     GEG    CM    AB   NaN    16   
26   1921     GEG    CM    AB   NaN    17   
27   1921     GEG    CM    AB   NaN    18   
28   1921     GEG    CM    AB   NaN    19   
29   1921     GEG    CM    AB   NaN    20   
30   1921     GEG    CM    AB   NaN    21   
31   1921     GEG    CM    AB   NaN    22   
32   1921     GEG    CM    AB   NaN    23   
33   1921     GEG    CM    AB   NaN    24   
34   1921     GEG    CM    AB   NaN    25   
35   1921     GEG    OM    HL    IN     1   
36   1921     GEG    OM    HL    IN     2   
37   1921     GEG    OM    HL    IN     3   
38   1921     GEG    OM    HL    IN     4   
39   1921     GEG    OM    HL    IN     5   
40   1921     GEG    OM    HL    IN     6   
41   1921     GEG    OM    HL    IN     7   
42   1921     GEG    OM    HL    IN     8   
43   1921     GEG    OM    HL    IN     9   
44   1921     GEG    OM    HL    IN    10   
45   1921     GEG    OM    HL    IN    11   
46   1921     GEG    OM    HL    IN    12   
47   1921     GEG    OM    HL    IN    13   
48   1921     GEG    OM    HL    IN    14   
49   1921     GEG    OM    HL    IN    15   
50   1921     GEG    OM    HL    IN    16   
51   1921     GEG    OM    HL    IN    17   
52   1921     GEG    OM    HL    IN    18   
53   1921     GEG    OM    HL    IN    19   
54   1921     GEG    OM    HL    IN    20   
55   1921     GEG    OM    HL    IN    21   
56   1921     GEG    OM    HL    IN    22   
57   1921     GEG    OM    HL    IN    23   
58   1921     GEG    OM    HL    IN    24   
59   1921     GEG    OM    HL    IN    25   
60   1921     GEG    OM    HL    IN    26   
61   1921     GEG    OM    HL    IN    27   
62   1921     GEG    OM    HL    IN    28   
63   1921     GEG    OM    HL    IN    29   
64   1921     GEG    OM    HL    IN    30   
65   1921     GEG    OM    HL    IN    31   
66   1921     GEG    OM    HL    IN    32   
67   1921     GEG    OM    HL    IN    33   
68   1921     GEG    OM    HL    IN    34   
69   1921     GEG    OM    HL    IN    35   
70   1921     GEG    OM    HL    IN    36   
71   1921     GEG    OM    HL    IN    37   
72   1921     GEG    OM    HL    IN    38   
73   1921     GEG    OM    HL    IN    39   
74   1921     GEG    OM    HL    IN    40   
75   1921     GEG    OM    HL    IN    41   
76   1921     GEG    OM    HL    IN    42   
77   1921     GEG    OM    HL    IN    43   
78   1921     GEG    OM    HL    IN    44   
79   1921     GEG    OM    HL    IN    45   
80   1921     GEG    OM    HL    IN    46   
81   1921     GEG    OM    HL    IN    47   
82   1921     GEG    OM    HL    IN    48   
83   1921     GEG    OM    HL    IN    49   
84   1921     GEG    OM    HL    IN    50   
85   1921     GEG    OM    HL    IN    51   
86   1921     GEG    OM    HL    IN    52   
87   1921     GEG    OM    HL    IN    53   


In [391]:
#I'll export the main df into a .csv 
df_main = df_main.drop([0])

filepath = Path(f'Output/{society}/{year}_{society}_Members_Raw.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
df_main.to_csv(filepath) 

## GGuA

### Section Tagging

##### manual changes: 

- NB: File 1876_GGuA_New.txt does not have a list of members or corresponding associations.
- in file 1877-1881_GGuA_New.txt I manually remove the line break from line 1623.
- NB: File 1877-1881_GGuA_New.txt does not have a list of members or corresponding associations. --> Separate this into its individual years. 
- in file 1882-1883_GGuA_New.txt I manually removed the line break from line 3651 and moved the date to the end of the line.
- NB: The last section in file 1884_GGuA_New.txt includes a yearly report as well as a summary and description of the 50th anniversary of the society. They are currently not marked separately.  
- in file 1885_GGuA_New.txt I manually removed the line break from line 3788, because this list belongs to one of the sections and not the overall organisational aspects of the society. 
- in file 1888_GGuA_New.txt I manually remove the spaces from line 5127. 
- NB: There are no specifically marked public yearly meetings in 1884, 1893, 1895, 1896 and between 1888-1891. 
- in file 1885_GGuA_New.txt I manually removed the line break from line 3901.
- in file 1900_GGuA_New.txt I manually correct the title of the first section in line 28.
- in file 1900_GGuA_New.txt I manually remove the additional spaces from line 10210.
- in file 1901_GGuA_New.txt I manually correct the title of the first section in line 28.
- in file 1901_GGuA_New.txt I manually remove the additional spaces from line 6964.
- NB: In file 1903_GGuA_New.txt there are two yearly meetings and additional lists. 
- in file 1907_GGuA_New.txt I manually adapt the section tiles for octobre and novembre from "Sitzung" to "Versammlung in line 2767 and line 3335.
- in file 1908_GGuA_New.txt I manually adapt some section tiles from "Sitzung" to "Versammlung in line 27, line 301, line 827 and line 1024.
- in file 1909_GGuA_New.txt I manually adapt some section tiles from "Sitzung" to "Versammlung in line 1148 and line 1453.
- in file 1909_GGuA_New.txt I manually remove the line break from line 3021.
- in file 1911_GGuA_New.txt I manually remove the line break from line 16700.

##### Code:

In [295]:
#I read the file into a list
year = '1914'
filename = f'Sources/GGuA/{year}_GGuA_New.txt'
with open(filename, 'r') as fp:
    text = fp.readlines()
    

In [297]:
#I check whether all the sections I want to tag are being detected. 
#I try to adjust the parameters as best as possible to capture all sections.
#If I do notice missing sections I have to check the file manually and adapt the lines if needed.

for num, line in enumerate(text, 1):
                                
    section_score = fuzz.ratio('760. Sitzung am 11. März 1914.', line)                                    #I adjust this as best I can to what the ideal outcome would be
    yearly_score = fuzz.ratio('770. (Jahres-) Sitzung am 6. December 1914.', line)
    list_mem_score = fuzz.ratio('Verzeichnis der Mitglieder \n', line)
    list_score = fuzz.ratio('Verzeichnis \n', line)
     
    if section_score >= 60:                                                              #I tweak the score until it fits best
        print(f"Section: {line}; Score: {section_score}; in Line: {num}")
    elif list_mem_score >= 90:                                                           #I tweak the score until it fits best
        print(f"Members List: {line}; Score: {list_mem_score}; in Line: {num}")
    elif list_score >= 90:                                                               #I tweak the score until it fits best
        print(f"List: {line}; Score: {list_score}; in Line: {num}")
    elif yearly_score >= 60:                                                             #I tweak the score until it fits best
        print(f"Yearly: {line}; Score: {yearly_score}; in Line: {num}")

Section: 7(6. Sitzung am 8. Januar 1914. 
; Score: 76; in Line: 93
Section: 767, Sitzimg am 12. Februar 1914. 
; Score: 68; in Line: 406
Section: 768. Sitzung am 12. März 1914. 
; Score: 90; in Line: 826
Section: 769. Sitzung am 9. April 1914, 
; Score: 74; in Line: 1690
Section: 770. Sitzung am 14. Mai 1914. 
; Score: 82; in Line: 2764


In [290]:
#I create a new list with the lines that mark sections being tagged.
#I have to adjust the changes made above

new_text = []
 
new_text.append("<section type='beginning'> ")

for num, line in enumerate(text, 0):
    
    section_score = fuzz.ratio('760. Sitzung am 11. März 1914.', line)                                    #I adjust this as best I can to what the ideal outcome would be
    yearly_score = fuzz.ratio('770. (Jahres-) Sitzung am 6. December 1914.', line)
    list_mem_score = fuzz.ratio('Verzeichnis der Mitglieder \n', line)
    list_score = fuzz.ratio('Verzeichnis \n', line)
     
         
    if section_score >= 60:
        new_text.append("</section>\n")                                #since this is repeating I have to close the section as well, but I also close a section before the first ever starts...
        ano_line = f"<section type='monthlymeet'> {line}"
        new_text.append(ano_line)
        
    elif yearly_score >= 60:
        new_text.append("</section>\n")                                 #I close the section tag with an additional line before the new section starts 
        ano_line = f"<section type='yearlymeet'> {line}"                 #I open the section tag in the line I detected
        new_text.append(ano_line)
        
    elif list_mem_score >= 90:
        new_text.append("</section>\n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)    
        
    elif list_score >= 90:
        new_text.append("</section>\n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)
        
    else:
        new_text.append(line)
        
new_text.append("</section>\n")                                         #I close the very last section 


In [291]:
new_text[:60]

["<section type='beginning'> ",
 '!#•* \n',
 'Sitiniisberiekte \n',
 'der \n',
 '""\'"für6eschicliteind Altertumskundeder\n',
 'Ostseeprovinzen Russlands \n',
 'aus dem Jahre 1912. \n',
 'Hierzu 1 Porträt und 4 Tafeln. \n',
 "K' / i \n",
 'Riga. \n',
 'Drnck von W. F. Bäcker . \n',
 '1914. \n',
 '1 \n',
 'Gedruckt auf Verfügen des Direktoriums der Gesellschaft für Geechichte \n',
 'und Altertumskunde der Osteeeprovinzen Russlands. \n',
 'Präsident: Arnold Feuere i sen . \n',
 'R iga , den 23. Juli 1913. \n',
 'fy~d. $ \n',
 '$>ч *3 jbf \n',
 'Inhaltsanzeige. \n',
 's eite \n',
 'Sitzungsberichte aus dem Jahre 1912 1 \n',
 'Jahresbericht des Sekretärs der Gesellschaft , . . . 406 \n',
 'Verzeichnis der Vereine und Anstalten, denen die Schriften der \n',
 'Gesellschaft übersandt worden sind, mit Angabe der im Austausch \n',
 'von ihnen erhaltenen Druckwerke 448 \n',
 'Vorstand der Gesellschaft im Jahre 1912 460 \n',
 'Verzeichnis der Mitglieder am 6. Dezember 1912 461 \n',
 'Verzeichnis 

In [292]:
#I write the new annotated list into a .txt file 

out_filename = f'Output/GGuA/{year}_GGuA_Ano.txt'                        

filepath = Path(out_filename)                             
filepath.parent.mkdir(parents=True, exist_ok=True)                       #creates the folders if they don't exist yet

with open(out_filename, 'x') as fp:                                      #"x" to not overwrite already existing files by accident
    fp.write("".join(str(item) for item in new_text))

### Seperating multiple years

In [357]:
#To separate file 1877-1881_GGuA_Ano.txt and file 1882-1883_GGuA_Ano.txt in its individual years
#I once more check where the sections start and end, writing down the parameters of the year splits. 

filename = f'Output/GGuA/1882-1883_GGuA_Ano.txt'
with open(filename, 'r') as fp:
    text = fp.readlines()


for num, line in enumerate(text, 1):
                                
    section_score = fuzz.ratio("<section type='monthlymeet'> 410. Versammlung am 11. April 1877.", line)                                    #I adjust this as best I can to what the ideal outcome would be
    yearly_score = fuzz.ratio("<section type='yearlymeet'> 420. Versammlung. Oeffentliche Jahressitzung am 6. December 1877.", line)
    list_mem_score = fuzz.ratio('Verzeichnis der Mitglieder \n', line)
    list_score = fuzz.ratio('Verzeichnis \n', line)
     
    if section_score >= 60:                                                              #I tweak the score until it fits best
        print(f"Section: {line}; Score: {section_score}; in Line: {num}")
    elif list_mem_score >= 80:                                                           #I tweak the score until it fits best
        print(f"Members List: {line}; Score: {list_mem_score}; in Line: {num}")
    elif list_score >= 89:                                                               #I tweak the score until it fits best
        print(f"List: {line}; Score: {list_score}; in Line: {num}")
    elif yearly_score >= 70:                                                               #I tweak the score until it fits best
        print(f"Yearly: {line}; Score: {yearly_score}; in Line: {num}")

Section: <section type='monthlymeet'> 466. Veriüammlung am 13. Jannar 1882. 
; Score: 82; in Line: 36
Section: <section type='monthlymeet'> 467. VersamniloDg am 10. Febrnar 1882. 
; Score: 78; in Line: 115
Section: <section type='monthlymeet'> 468. Ifersammlnng am 10. März 1882. 
; Score: 82; in Line: 258
Section: <section type='monthlymeet'> 468. Versammlung am 10. März 1883. 
; Score: 85; in Line: 327
Section: <section type='monthlymeet'> 469. Versammlnng am 14. April 1882. 
; Score: 89; in Line: 461
Section: <section type='monthlymeet'> 470. Versammlung am 12. Mai 1882. 
; Score: 88; in Line: 512
Section: <section type='monthlymeet'> 471. Versammlnng am 8. September 1883. 
; Score: 83; in Line: 637
Section: <section type='monthlymeet'> 472. Versammlnng am 13. Oetober 1882. 
; Score: 82; in Line: 881
Section: <section type='monthlymeet'> 473. Versammlung am 10. November 1882. 
; Score: 83; in Line: 990
Section: <section type='monthlymeet'> 474. Tersammiang am 4. Deeember 1881 
; Scor

In [359]:
#I get the last line marking the end of the las year split
print(len(text))

5572


In [356]:
#I defined a function to do the spliting
#In test=True mode I can check the lines
#In test=False mode I create a separate file

def split_years(full_text, out_filename, start_num, end_num, test=False):
    ''' This function splits a list (var=text) in individual text sections. '''
    split_text = []
    for num, line in enumerate(full_text,0):
        if num in range(start_num, end_num):
            split_text.append(line)
    if test == True:
        return split_text
    else:                    
        with open(out_filename, 'x') as fp: 
            fp.write("".join(str(item) for item in split_text))

In [371]:
#I use the function for all 6 years
#1877 = 0 - 1860
#1878 = 1860 - 3393
#1879 = 3393 - 4576
#1880 = 4576 - 5935
#1881 = 5935 - 7027
#1882 = 0 - 1395
#1883 = 1395 - 5572

filename = f'Output/GGuA/1882-1883_GGuA_Ano.txt'
with open(filename, 'r') as fp:
    full_text = fp.readlines()

year = "1883"
out_filename = f'Output/GGuA/{year}_GGuA_Ano.txt'
start_num = 1395
end_num = 5572

split_years(full_text, out_filename, start_num, end_num, test=False)


### Isolating and annotating membership list

#### Code

In [67]:
#I read the file into a list
year = "1914"
filename = f'Output/GGuA/{year}_GGuA_Ano.txt'
with open(filename, 'r') as fp:
    text = fp.readlines()
    

In [68]:
#I look for the section markers and write them in lists
#Same as GEG

sections_s = []
sections_e = []

for num, line in enumerate(text, 0):
    if line.startswith("<section type='list'>"):                           #Only section beginnings with marker "list".
        sections_s.append(num)
        
for num, line in enumerate(text, 1):        
    if line == "</section>\n":                                            #All section endings are the same.
        sections_e.append(num)
        
print(sections_s)
print(sections_e)

[]
[93, 407, 828, 1693, 2768, 8753]


In [62]:
#I check which of the list sections is the membership list and create a list only with this section
#Same as GEG
members_text = text[sections_s[1]:sections_e[-4]]
members_text

["<section type='list'> Verzeichnis der Mitglieder*). \n",
 'I. Ehrenmitglieder. \n',
 '1. Präsident der Kaiserlichen Archäologischen Gesellschaft zu \n',
 'Moskau Gräfin Praskowja Sergejewna Uwarow. 1894. Въ \n',
 'Императорское Археологическое Общество. Москва. \n',
 '2. К. К. Hofrat u. Universitätsprofessor а. D., Mitglied des \n',
 'Herrenhauses Dr. Stanislaus Smolka. 1894. Galizien, Sehl. \n',
 'Niegoszowice I. P. Rudawa. \n',
 '3. Wirkl. Staatsrat Professor emer. Dr. hist. Richard Hausmann. \n',
 '1895. Dorpat, Lehmstrasse 2. Derzeitiges Mitglied des \n',
 'Direktoriums der Gesellschaft. \n',
 '4. Direktor des Alten Archivs der Livländischen Ritterschaft \n',
 'Hermann Baron Bruiningk. 1902. Riga, Thronfolgerboulevard 23. \n',
 'Derzeitiges Mitglied des Direktoriums der Gesellschaft. \n',
 '5. Universitätsbibliothekar a. D. Dr. Wolfgang Schlüter. 1908. \n',
 'Dorpat, Mühlenstr. 11. \n',
 '6. Schuldirektor a. D. Gotthard Schweder. 1908. Riga, Peter-\n',
 'Paulstrasse 2. \n',
 '7. 

In [63]:
#Alsmost the same as GEG 
#adapting the comparison strings for HM, CM, and OM
#adding the additional marker Prinzipale as PM

#First round annotating the membership list
#I again use XML inspired tags to mark the structuring elements of the list.
#This is the first level of information including the status of their membership: honorable, ordinary or corresponding.
#Depending on the quality of the OCR these reference words need to be adapted.

members_ano_1 = []
for line in members_text: 
    hon_mem = fuzz.ratio("I. Ehren-Mitglieder. ", line)                            
    cor_mem = fuzz.ratio("II. Correspondierende Mitglieder. ", line) 
    pri_mem = fuzz.ratio("III. Prinzipale. ", line)
    ord_mem = fuzz.ratio("IV. Ordentliche Mitglieder. ", line) 
    
    if hon_mem >= 80:
        members_ano_1.append("<members>")                                          #I open members section
        members_ano_1.append(f"<honorable_members> {line}")                        #I open honorable members section
        print("HM detected")
        
    elif cor_mem >=80:
        #members_ano_1.append("</ordinary_members>")
        #members_ano_1.append("</principal_members>")
        members_ano_1.append("</honorable_members>")
        members_ano_1.append(f"<corresponding_members> {line}")                    #I open corresponding members section
        print("CM detected")
        
    elif pri_mem >= 70:
        members_ano_1.append("</honorable_members>")                               #I close honorable members section
        #members_ano_1.append("</corresponding_members>")
        members_ano_1.append(f"<principal_members> {line}")                         #I open ordinary members section
        print("PM detected")
        
    elif ord_mem >= 70:
        #members_ano_1.append("</honorable_members>")                               #I close honorable members section
        members_ano_1.append("</corresponding_members>")
        #members_ano_1.append("</principal_members>")
        members_ano_1.append(f"<ordinary_members> {line}")                         #I open ordinary members section
        print("OM detected")
        
    elif line == "</section>\n":
        #members_ano_1.append("</corresponding_members>")                           #I close corresponding members section
        members_ano_1.append("</ordinary_members>")
        members_ano_1.append("</members>")                                         #I close members section
        members_ano_1.append(line)
        print("Section tag detected")
    
    else:                                                                          #Don't forget to also append the rest of the original list
        members_ano_1.append(line)
        
members_ano_1

HM detected
CM detected
OM detected
Section tag detected


["<section type='list'> Verzeichnis der Mitglieder*). \n",
 '<members>',
 '<honorable_members> I. Ehrenmitglieder. \n',
 '1. Präsident der Kaiserlichen Archäologischen Gesellschaft zu \n',
 'Moskau Gräfin Praskowja Sergejewna Uwarow. 1894. Въ \n',
 'Императорское Археологическое Общество. Москва. \n',
 '2. К. К. Hofrat u. Universitätsprofessor а. D., Mitglied des \n',
 'Herrenhauses Dr. Stanislaus Smolka. 1894. Galizien, Sehl. \n',
 'Niegoszowice I. P. Rudawa. \n',
 '3. Wirkl. Staatsrat Professor emer. Dr. hist. Richard Hausmann. \n',
 '1895. Dorpat, Lehmstrasse 2. Derzeitiges Mitglied des \n',
 'Direktoriums der Gesellschaft. \n',
 '4. Direktor des Alten Archivs der Livländischen Ritterschaft \n',
 'Hermann Baron Bruiningk. 1902. Riga, Thronfolgerboulevard 23. \n',
 'Derzeitiges Mitglied des Direktoriums der Gesellschaft. \n',
 '5. Universitätsbibliothekar a. D. Dr. Wolfgang Schlüter. 1908. \n',
 'Dorpat, Mühlenstr. 11. \n',
 '6. Schuldirektor a. D. Gotthard Schweder. 1908. Riga, Pete

In [64]:
#GGuA does not have further structural levels. 

#Same as GEG
#First step of the cleaning process of the membership list
#Adjust Ano numbers in case third level structure was skipped

members_ano_2 = []

for line in members_ano_1:
    if line.startswith("— "):                      #I remove the page number markers 
        members_ano_1.remove(line)

for line in members_ano_1:
    new_line = re.sub("\n", "", line)             #I remove the line breaks to reconnect information about one person that is split in two lines.
    members_ano_2.append(new_line)

        
#members_ano_2

In [65]:
#Same as GEG
#Second step of the cleaning process of the membership list
#NB! This is only possible if all members have a clear marker at the beginning --> Some files have OCR errors here. 

members_ano_3 = []

for line in members_ano_2:
    if line.startswith("<"):
        new_line = re.sub(r"<", r"\n<", line)                 #I insert a line break before each marker
        members_ano_3.append(new_line)
    else:
        new_line = re.sub(r"^(\S{1,3})\.", r"\n\1)", line, 1)      #I insert a number before each number signifying a person ( I remove the ^ denoting the beginning of the line only for members list 1921.
        members_ano_3.append(new_line)                             #I should have remembered to reinsert the ^ again for these a lot of manual changes until 1895 would not have been necessary...
        
#members_ano_3

In [66]:
out_filename = f'Output/GGuA/{year}_GGuA_Members_Ano.txt'                

filepath = Path(out_filename)                             
filepath.parent.mkdir(parents=True, exist_ok=True)                  #creates the folders if they don't exist yet

with open(out_filename, 'x') as fp:
    fp.write("".join(str(item) for item in members_ano_3))          #By joining the list elements without any symbol the 
                                                                    #line breaks will be at the end of each line the next time I read the document in 

#### manual changes

- In file 1873_GGuA_Members_Ano.txt I manually correct falsely formated start numbers.  
- In file 1873_GGuA_Members_Ano.txt I manually removed the note regarding membership fees from line 70.  
- In file 1873_GGuA_Members_Ano.txt I manually removed the note regarding the "Stifter" from line 90. 
- In file 1874_GGuA_Ano.txt I manually insert the structural marker "I. Ehrenmitglieder." in line 2913.
- In file 1874_GGuA_Ano.txt I manually correct the structural marker "II. Correspondierende Mitglieder." in line 2955, as well as the strucutral marker "III. Principale." in line 3013, and "IV. Ordentliche Mitglieder." in line 3021. (The OCR is too bas to be recognicable with the fuzz.ration.) 
- In file 1874_GGuA_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1874_GGuA_Members_Ano.txt I manually removed the note regarding the membership corrections from line 176ff.
- In file 1875_GGuA_Ano.txt I manually insert the structural marker "I. Ehrenmitglieder." in line 3395.
- In file 1875_GGuA_Ano.txt I manually correct the structural marker "II. Correspondierende Mitglieder." in line 3439, as well as the strucutral marke "IV. Ordentliche Mitglieder." in line 3510. (The OCR is too bas to be recognicable with the fuzz.ration.) 
- In file 1875_GGuA_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1875_GGuA_Members_Ano.txt I manually correct line 5 (person 1). 
- In file 1875_GGuA_Members_Ano.txt I manually removed the note regarding the deseased members and membership corrections from line 198ff.
- NB: File 1876_GGuA_Ano.txt does not have a membership list. 
- NB: File 1877_GGuA_Ano.txt does not have a membership list. 
- NB: File 1878_GGuA_Ano.txt does not have a membership list. 
- NB: File 1879_GGuA_Ano.txt does not have a membership list. 
- NB: File 1880_GGuA_Ano.txt does not have a membership list. 
- NB: File 1881_GGuA_Ano.txt does not have a membership list. 
- NB: File 1882_GGuA_Ano.txt does not have a membership list. 
- In file 1883_GGuA_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1883_GGuA_Members_Ano.txt I manually remove the note in line 214f. 
- In file 1884_GGuA_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1884_GGuA_Members_Ano.txt I manually remove the note in line 272f.
- In file 1885_GGuA_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1885_GGuA_Members_Ano.txt I manually remove the note in line 278f.
- In file 1886_GGuA_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1886_GGuA_Members_Ano.txt I manually remove the note in line 275f.
- In file 1886_GGuA_Members_Ano.txt I manually correct line 121 (person 59).
- In file 1887_GGuA_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1887_GGuA_Members_Ano.txt I manually remove the note in line 293f.
- In file 1888_GGuA_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1888_GGuA_Members_Ano.txt I manually remove the note in line 312f.
- In file 1889_GGuA_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1889_GGuA_Members_Ano.txt I manually remove the note in line 286f.
- In file 1890_GGuA_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1890_GGuA_Members_Ano.txt I manually remove the note in line 248f.
- In file 1891_GGuA_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1891_GGuA_Members_Ano.txt I manually remove the note in line 319f.
- In file 1892_GGuA_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1882_GGuA_Members_Ano.txt I manually correct line 22 (person 1).
- In file 1892_GGuA_Members_Ano.txt I manually remove the note in line 341f.
- In file 1893_GGuA_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1893_GGuA_Members_Ano.txt I manually correct line 24 (person 1).
- In file 1893_GGuA_Members_Ano.txt I manually remove the note in line 480f.
- In file 1894_GGuA_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1894_GGuA_Members_Ano.txt I manually correct line 23 (person 1).
- In file 1894_GGuA_Members_Ano.txt I manually remove the note in line 521f.
- In file 1895_GGuA_Members_Ano.txt I manually correct line 24 (person 1).
- In file 1896_GGuA_Members_Ano.txt I manually correct line 21 (person 1).
- In file 1896_GGuA_Members_Ano.txt I manually correct falsely formated start numbers in line 286, and line 520.
- In file 1896_GGuA_Members_Ano.txt I manually remove the note in line 565.
- In file 1897_GGuA_Members_Ano.txt I manually correct line 20 (person 1), and line 145 (person 85-90).
- In file 1897_GGuA_Members_Ano.txt I manually correct falsely formated start numbers in line 508, and in line 556.
- In file 1897_GGuA_Members_Ano.txt I manually remove the note in line 566.
- In file 1898_GGuA_Members_Ano.txt I manually correct falsely formated start numbers in line 11, in line 99, in line 531, and line 549.
- In file 1898_GGuA_Members_Ano.txt I manually correct line 18 (person 1).
- In file 1898_GGuA_Members_Ano.txt I manually remove the note in line 561.
- In file 1899_GGuA_Members_Ano.txt I manually correct line 19 (person 1), and in line 366 (person 310).
- In file 1899_GGuA_Members_Ano.txt I manually correct falsely formated start numbers in line 31, in line 42, in line 136, in line 200, in line 240, in line 309, in line 351, in line 470, and in line 552.
- In file 1899_GGuA_Members_Ano.txt I manually remove the note in line 561.
- In file 1900_GGuA_Members_Ano.txt I manually correct line 17 (person 1).
- In file 1900_GGuA_Members_Ano.txt I manually correct falsely formated start numbers in line 29, in line 40, in line 131, in lin 194, in line 232, in line 296, in line 337, in lien 457, in line 535, in line 553, and in line 565. 
- In file 1900_GGuA_Members_Ano.txt I manually remove the note in line 577.
- In file 1901_GGuA_Members_Ano.txt I manually correct line 16 (person 1).
- In file 1901_GGuA_Members_Ano.txt I manually correct falsely formated start numbers in line 26, in line 40, in line 86, in line 172, in line 248, in line 271, in line 290, in line 389, in line 466, in line 487, in line 492, in line 502, and in line 529.
- In file 1901_GGuA_Members_Ano.txt I manually remove the note in line 566.
- In file 1902_GGuA_Members_Ano.txt I manually correct line 16 (person 1).
- In file 1902_GGuA_Members_Ano.txt I manually correct falsely formated start numbers in line 103, in line 180, in line 191, in line 279, in line 300, in line 301, in line 419, in line 492, in line 510, and in line 545.
- In file 1902_GGuA_Members_Ano.txt I manually remove the note in line 548.
- In file 1903_GGuA_Members_Ano.txt I manually correct line 16 (person 1).
- In file 1903_GGuA_Members_Ano.txt I manually remove the note in line 16, and line 588.
- In file 1903_GGuA_Members_Ano.txt I manually correct falsely formated start numbers in line 37, in line 65, in line 72, in line 123, in line 126, in line 147, in line 177, in line 189, in line 196, in line 227, in line 250, in line 282, in line 303, in line 304, in line 323, in line 348, in line 449, in line 498, in line 507, in line 513, in line 519, and in line 548.
- In file 1904_GGuA_Members_Ano.txt I manually correct falsely formated start numbers in line 36, in line 40, in line 64, in line 87, in line 112, in line 120, in line 123, in line 146, in line 188, in line 225, in line 251, in line 284, in line 304, in line 325, in line 450, in line 498, in line 507, in line 512, in line 513, in line 516, in line 519, in line 547, and in line 577.
- In file 1904_GGuA_Members_Ano.txt I manually correct line 16 (person 1).
- In file 1904_GGuA_Members_Ano.txt I manually remove the note in line 16, and in line 585. 
- In file 1905_GGuA_Members_Ano.txt I manually correct falsely formated start numbers in line 8, in line 35, in line 60, in line 115, in line 118, in line 137, in line 175, in line 207, in line 218, in line 263, in line 283, in line 303, in line 340, in line 418, in line 461, in line 470, in line 474, in line 475, in line 480, in line 482, in line 488, in line 509, and in line 510.
- In file 1905_GGuA_Members_Ano.txt I manually correct line 16 (person 1), line 117 (person 72), line 136 (person 94), line 217 (person 180), and line 222 (person 185-186).   
- In file 1905_GGuA_Members_Ano.txt I manually remove the note in line 16, and in line 550. 
- In file 1906_GGuA_Members_Ano.txt I manually correct line 15 (person 1), line 398 (person 347)
- In file 1906_GGuA_Members_Ano.txt I manually remove the note in line 15, and in line 513.
- In file 1906_GGuA_Members_Ano.txt I manually correct falsely formated start numbers in line 35, in line 60, in line 130, in line 131, in line 166, in line 192, in line 205, in line 245, in line 283, in line 318, in line 323, in line 346, in line 389, in line 428, in line 437, in line 441, in line 442, in line 449, in line 476, in line 508.
- In file 1907_GGuA_Members_Ano.txt I manually correct line 15 (person 1).
- In file 1907_GGuA_Members_Ano.txt I manually remove the note in line 15, and in line 498.
- In file 1907_GGuA_Members_Ano.txt I manually correct falsely formated start numbers in line 34, in line 38, in line 59, in line 126, in line 157, in line 199, in line 238, in line 277, in line 315, in line 334, in line 381, in line 418, in line 427, in line 431, in line 432, in line 445, in line 462, and in line 493.
- In file 1908_GGuA_Members_Ano.txt I manually correct line 20 (person 1).
- In file 1908_GGuA_Members_Ano.txt I manually remove the note in line 14, and in line 493.
- In file 1908_GGuA_Members_Ano.txt I manually correct falsely formated start numbers in line 36, in line 60, in line 99, in line 119, in line 120, in line 152, in line 192, in line 231, in line 265, in line 268, in line 298, in line 316, in line 326, in line 371, in line 411, in line 421, in line 425, in line 426, in line 454, in line 463, and in line 481.
- In file 1909_GGuA_Members_Ano.txt I manually remove the note in line 14, and in line 486.
- In file 1909_GGuA_Members_Ano.txt I manually correct falsely formated start numbers in line 118, in line 147,in line 149, in line 181, in line 230, in line 294, in line 316, in line 336, in line 362, in line 403, in line 414, in line 419, in line 439, in line 448, in line 450, in line 457, and in line 479.
- In file 1909_GGuA_Members_Ano.txt I manually correct line 197 (person 147).
- In file 1910_GGuA_Members_Ano.txt I manually remove the note in line 14, and in line 492.
- In file 1910_GGuA_Members_Ano.txt I manually correct falsely formated start numbers in line 117, in line 147, in line 149, in line 183, in line 231, in line 299, in line 321, in line 341, in line 370, in line 412, in line 425, in line 430, in line 448, in line 455, in line 464, and in line 485.
- In file 1911_GGuA_Members_Ano.txt I manually remove the note in line 14, and in line 494.
- In file 1911_GGuA_Members_Ano.txt I manually correct falsely formated start numbers in line 52, in line 111, in line 123, in line 135, in line 151, in line 153, in line 188, in line 190, in line 238, in line 306, in line 323, in line 332, in line in line 347, in line 376, in line 427, in line 432, in line 457, in line 461, in line 465, and in line 487.
- In file 1912_GGuA_Members_Ano.txt I manually remove the note in line 14, and in line 505.
- In file 1912_GGuA_Members_Ano.txt I manually correct falsely formated start numbers in line 49, in line 56, in line 127, in line 158, in line 192, in line 197, in line 223, in line 247, in line 278, in line 290, in line 307, in line 318, in line 326, in line 337, in line 341, in line 351, in line 362, in line 363, in line 386, in line 390, in line 445, in line 476, and in line 499.
- In file 1913_GGuA_Members_Ano.txt I manually remove the note in line 14, and in line 508.
- In file 1913_GGuA_Members_Ano.txt I manually correct falsely formated start numbers in line 51, in line 58, in line 129, in line 158, in line 188, in line 193, in line 224, in line 269, in line 281, in line 293, in line 309, in line 321, in line 331, in line 337, in line 341, in line 345, in line 354, in line 365, in line 366, in line 389, in line 394, and in line 449. 
- In file 1913_GGuA_Members_Ano.txt I manually correct line 187 (person 132).


### Extracting Information in a df and .csv

In [249]:
#Same as GEG
#I read the file into a list
year = "1913"
society = "GGuA"

filename = f'Output/{society}/{year}_{society}_Members_Ano.txt'
with open(filename, 'r') as fp:
    text = fp.readlines()

In [250]:
#Adjusted from GEG
#I figure out the start and endpoints of each of the section so I can later use these to ascribe membership status information in each row

#Honorable Members 
for num, line in enumerate(text, 0):
    if line.startswith("<honorable_members>"):                    #The opening marker gives the number for the starting point of the iteration of the list.
        start_hm = num +1                                         #+1 to start without the structural tag of this section
        #print(f"{start_hm}: {line}")
    if line == "</honorable_members>\n":                          #The closing marker gives the number for the end point of the iteration of the list.
        end_hm = num                                                          
        #print(f"{end_hm}: {line}")


#Principal Members
for num, line in enumerate(text, 0):
    if line.startswith("<principal_members>"):
        start_pm = num +1
        #print(f"{start_cm}: {line}")
    if line == "</principal_members>\n":
        end_pm = num    
        #print(f"{end_cm}: {line}")
        
        
#Corresponding Members
for num, line in enumerate(text, 0):
    if line.startswith("<corresponding_members>"):
        start_cm = num +1
        #print(f"{start_cm}: {line}")
    if line == "</corresponding_members>\n":
        end_cm = num    
        #print(f"{end_cm}: {line}")
        

#Ordinary Members       
for num, line in enumerate(text, 0):
    if line.startswith("<ordinary_members>"):
        start_om = num +1
        #print(f"{start_om}: {line}")
    if line == "</ordinary_members>\n":
        end_om = num
        #print(f"{end_om}: {line}")


In [251]:
#Same as GEG (I keep the additional structural levels for comparability between the societies even though the GGuA only has a 1st level descriptor) 
#I create an empty data frame to which I will add the individual rows of members

df_main = pd.DataFrame()                                                                                         #Without this it gives me an error that df is not defined in index section
df_main = pd.DataFrame(index = [len(df_main.values)],                                                             #index should count up from 1 to the number of values currently in df
                  columns = ['YEAR', 'SOCIETY', '1L_MS', '2L_MS', '3L_MS', 'NO_MS', 'LINE']) 
df_main

YEAR SOCIETY 1L_MS 2L_MS 3L_MS NO_MS LINE
0  NaN     NaN   NaN   NaN   NaN   NaN  NaN

In [252]:
#Adjusted from GEG (removed additional structural level and added principal members) 

#I go through each file by each section and create a df for each person 
#Splitting a line by its number spearating it from the sole "text" section 
#The df of a row includes "YEAR", "SOCIETY", "1L_MS", ("2L_MS", "3L_MS"), "NO_MS, "LINE"
#I concat the main df with the row df to add the member 

for num, line in enumerate(text,0):
    
    #Honorable Members
    if num in range(start_hm, end_hm):
        
        row = line.split(")", 1)                                                                    #maxsplits set to 1 to only separate the line after the initial ")" and not further
            
        df_row = pd.DataFrame({"YEAR": year, "SOCIETY": society, "1L_MS": "HM", "NO_MS": row[0], "LINE": row[1]},
                                index = [len(df_main.values)],                                        
                                columns = ['YEAR', 'SOCIETY', '1L_MS', 'NO_MS', 'LINE'])
            
        df_main = pd.concat([df_main, df_row])
     
    
    #Principal Members                                                                              #Starting from 1909 there is no principal member anymore
    #if num in range(start_pm, end_pm):                                                             #I then have to comment out this section otherwise I get a double person one with HM and one with PM 
                                                                                                    #Really not sure where this is coming from because there is no start_pm or end_pm detected...
        #row = line.split(")",1)
            
        #df_row = pd.DataFrame({"YEAR": year, "SOCIETY": society, "1L_MS": "PM",  "NO_MS": row[0], "LINE": row[1]},
                                  #index = [len(df_main.values)],                                        
                                  #columns = ['YEAR', 'SOCIETY', '1L_MS', 'NO_MS', 'LINE'])
            
        #df_main = pd.concat([df_main, df_row])
            

    #Corresponding Members
    if num in range(start_cm, end_cm):
       
        row = line.split(")",1)
            
        df_row = pd.DataFrame({"YEAR": year, "SOCIETY": society, "1L_MS": "CM",  "NO_MS": row[0], "LINE": row[1]},
                                  index = [len(df_main.values)],                                        
                                  columns = ['YEAR', 'SOCIETY', '1L_MS', 'NO_MS', 'LINE'])
            
        df_main = pd.concat([df_main, df_row])
            
            
        
    #Ordinary Members
    if num in range(start_om, end_om):
        
        row = line.split(")",1)
            
        df_row = pd.DataFrame({"YEAR": year, "SOCIETY": society, "1L_MS": "OM",  "NO_MS": row[0], "LINE": row[1]},
                                  index = [len(df_main.values)],                                        
                                  columns = ['YEAR', 'SOCIETY', '1L_MS', 'NO_MS', 'LINE'])
            
        df_main = pd.concat([df_main, df_row])
                
            

In [253]:
pd.options.display.max_rows = 999
df_main

YEAR SOCIETY 1L_MS 2L_MS 3L_MS NO_MS  \
0     NaN     NaN   NaN   NaN   NaN   NaN   
1    1913    GGuA    HM   NaN   NaN     1   
2    1913    GGuA    HM   NaN   NaN     2   
3    1913    GGuA    HM   NaN   NaN     3   
4    1913    GGuA    HM   NaN   NaN     4   
5    1913    GGuA    HM   NaN   NaN     5   
6    1913    GGuA    HM   NaN   NaN     6   
7    1913    GGuA    HM   NaN   NaN     7   
8    1913    GGuA    HM   NaN   NaN     8   
9    1913    GGuA    HM   NaN   NaN     9   
10   1913    GGuA    HM   NaN   NaN    10   
11   1913    GGuA    HM   NaN   NaN    11   
12   1913    GGuA    HM   NaN   NaN    12   
13   1913    GGuA    HM   NaN   NaN    13   
14   1913    GGuA    HM   NaN   NaN    14   
15   1913    GGuA    HM   NaN   NaN    15   
16   1913    GGuA    HM   NaN   NaN    16   
17   1913    GGuA    HM   NaN   NaN    17   
18   1913    GGuA    HM   NaN   NaN    18   
19   1913    GGuA    HM   NaN   NaN    19   
20   1913    GGuA    HM   NaN   NaN    20   
21   1913    GGuA    CM   NaN   NaN     1   
22   1913    GGuA    CM   NaN   NaN     2   
23   1913    GGuA    CM   NaN   NaN     3   
24   1913    GGuA    CM   NaN   NaN     4   
25   1913    GGuA    CM   NaN   NaN     5   
26   1913    GGuA    CM   NaN   NaN     6   
27   1913    GGuA    CM   NaN   NaN     7   
28   1913    GGuA    CM   NaN   NaN     8   
29   1913    GGuA    CM   NaN   NaN     9   
30   1913    GGuA    CM   NaN   NaN    10   
31   1913    GGuA    CM   NaN   NaN    11   
32   1913    GGuA    CM   NaN   NaN    12   
33   1913    GGuA    CM   NaN   NaN    13   
34   1913    GGuA    CM   NaN   NaN    14   
35   1913    GGuA    CM   NaN   NaN    15   
36   1913    GGuA    CM   NaN   NaN    16   
37   1913    GGuA    CM   NaN   NaN    17   
38   1913    GGuA    CM   NaN   NaN    18   
39   1913    GGuA    CM   NaN   NaN    19   
40   1913    GGuA    CM   NaN   NaN    20   
41   1913    GGuA    CM   NaN   NaN    21   
42   1913    GGuA    CM   NaN   NaN    22   
43   1913    GGuA    CM   NaN   NaN    23   
44   1913    GGuA    CM   NaN   NaN    24   
45   1913    GGuA    CM   NaN   NaN    25   
46   1913    GGuA    CM   NaN   NaN    26   
47   1913    GGuA    CM   NaN   NaN    27   
48   1913    GGuA    CM   NaN   NaN    28   
49   1913    GGuA    OM   NaN   NaN     1   
50   1913    GGuA    OM   NaN   NaN     2   
51   1913    GGuA    OM   NaN   NaN     3   
52   1913    GGuA    OM   NaN   NaN     4   
53   1913    GGuA    OM   NaN   NaN     5   
54   1913    GGuA    OM   NaN   NaN     6   
55   1913    GGuA    OM   NaN   NaN     7   
56   1913    GGuA    OM   NaN   NaN     8   
57   1913    GGuA    OM   NaN   NaN     9   
58   1913    GGuA    OM   NaN   NaN    10   
59   1913    GGuA    OM   NaN   NaN    11   
60   1913    GGuA    OM   NaN   NaN    12   
61   1913    GGuA    OM   NaN   NaN    13   
62   1913    GGuA    OM   NaN   NaN    14   
63   1913    GGuA    OM   NaN   NaN    15   
64   1913    GGuA    OM   NaN   NaN    16   
65   1913    GGuA    OM   NaN   NaN    17   
66   1913    GGuA    OM   NaN   NaN    18   
67   1913    GGuA    OM   NaN   NaN    19   
68   1913    GGuA    OM   NaN   NaN    20   
69   1913    GGuA    OM   NaN   NaN    21   
70   1913    GGuA    OM   NaN   NaN    22   
71   1913    GGuA    OM   NaN   NaN    23   
72   1913    GGuA    OM   NaN   NaN    24   
73   1913    GGuA    OM   NaN   NaN    25   
74   1913    GGuA    OM   NaN   NaN    26   
75   1913    GGuA    OM   NaN   NaN    27   
76   1913    GGuA    OM   NaN   NaN    28   
77   1913    GGuA    OM   NaN   NaN    29   
78   1913    GGuA    OM   NaN   NaN    30   
79   1913    GGuA    OM   NaN   NaN    31   
80   1913    GGuA    OM   NaN   NaN    32   
81   1913    GGuA    OM   NaN   NaN    33   
82   1913    GGuA    OM   NaN   NaN    34   
83   1913    GGuA    OM   NaN   NaN    35   
84   1913    GGuA    OM   NaN   NaN    36   
85   1913    GGuA    OM   NaN   NaN    37   
86   1913    GGuA    OM   NaN   NaN    38   
87   1913    GGuA    OM   NaN   NaN    39   


In [254]:
#I'll export the main df into a .csv 
df_main = df_main.drop([0])

filepath = Path(f'Output/{society}/{year}_{society}_Members_Raw.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
df_main.to_csv(filepath) 

## NVR

### Year 1870-1880 
These yearly issues were published monthly and contain individual volumes with different sections and therefore need to be prepared differently

In [47]:
#I read the file into a list

year = '1872'
filename = f'Sources/NVR/{year}_NVR_New.txt'
with open(filename, 'r') as fp:
    text = fp.readlines()
    

In [48]:
#I adjust the comparison lines here so I only need to make adjustments here and not in the checking and annotating sections separately
#This is worked before because there were few changes to be made and few elements to detected
#But considereing the volume I extracted them out. 

volume = 'Druck von W. F. Häcker.'                   #Because of the different font for the start line of each volume, those lines have very(!) bad OCR. I therefore opted to look for the last line of each of these volumes. 
meetings = 'Sitzungen des Vereins.'
prints_list = 'Eingegangene Schriften.'
new_mem_list = 'Neuaufgenommene Mitglieder.'
metro_list = 'Eingegangene meteorologische Beobachtungen. '
observer_table = "Meteorologische Beobachtungen in Riga (N.Br. 56° 5?')."
observer_list = "Phänologisohe Beobachtungen "
yearly_report = "24sler Jahresbericht"

In [49]:
#I check what volumes and sections are being detected. 
#I try to adjust the parameters as best as possible to capture all volumes and sections.
#If I do notice missing sections I have to check the file and manually adapt the lines if needed.

vol_num = 0
for num, line in enumerate(text, 1):
                                
    volume_score = fuzz.ratio(volume, line)                                   
    meetings_score = fuzz.ratio(meetings, line)
    prints_list_score = fuzz.ratio(prints_list, line)
    new_mem_list_score = fuzz.ratio(new_mem_list, line)
    metro_list_score = fuzz.ratio(metro_list, line)
    observer_table_score = fuzz.ratio(observer_table, line)
    observer_list_score = fuzz.ratio(observer_list, line) 
    yearly_report_score = fuzz.ratio(yearly_report, line)
     
    if volume_score >= 70:                                                              
        print(f"Volume: {line}; Score: {volume_score}; in Line: {num}")
        vol_num += 1
    elif meetings_score >= 70:                                                             
        print(f"Meetings: {line}; Score: {meetings_score}; in Line: {num}")
    elif prints_list_score >= 70:                                                           
        print(f"Prints: {line}; Score: {prints_list_score}; in Line: {num}")
    elif new_mem_list_score >= 70:                                                         
        print(f"Members List: {line}; Score: {new_mem_list_score}; in Line: {num}")
    elif metro_list_score >= 70:                                                          
        print(f"Meteorological list: {line}; Score: {metro_list_score}; in Line: {num}")
    elif observer_table_score >= 70:                                                        
        print(f"Meteorological observations: {line}; Score: {observer_table_score}; in Line: {num}")
    elif observer_list_score >= 75:                                                    
        print(f"Phenological observations: {line}; Score: {observer_list_score}; in Line: {num}")
    elif yearly_report_score >= 70:                                      
        print(f"Yearly report: {line}; Score: {yearly_report_score}; in Line: {num}")   
print(vol_num)       

Meetings: Sitzungen des Vereins. 
; Score: 96; in Line: 172
Meteorological list: Eingegangene meteorologische Beobachtungen. 
; Score: 99; in Line: 631
Members List: Neuaufgenommene Mitglieder. 
; Score: 96; in Line: 636
Prints: Eingegangene Sohriften. 
; Score: 92; in Line: 645
Meteorological list: Meteorologische Beobachtungen in Riga. 
; Score: 71; in Line: 660
Meteorological observations: Meteorologische Beobachtungen in Riga (N. Br. 56° 59'). 
; Score: 95; in Line: 671
Meteorological observations: Meteorologische Beobachtungen in Riga (N. Br. 56° 59'). 
; Score: 95; in Line: 723
Meteorological observations: Meteorologische Beobachtungen in Riga (N.Br. 56° 59'). 
; Score: 96; in Line: 775
Volume: Druck von W. F. Hacker. 
; Score: 92; in Line: 821
Meetings: Sitzungen des Vereins. 
; Score: 96; in Line: 835
Phenological observations: Phänologische Beobachtungen aus dem Jahre 
; Score: 76; in Line: 1150
Meteorological list: Meteorologische Beobachtungen in Windau. 
; Score: 70; in Lin

In [15]:
#The structure of the NVR materials are vastly different to those of the GEG and GGuA. 
#Mainly in that each "Jahrgang" so yearly edition is seperated in different volumnes. 
#The content of each volume can be significantly different from each other. 
#I will therefore first annotate the volumes of a edition and then approach each volume to mark the content sections within. 

volume_text = []
i = 2 
volume_text.append(f"<volume year='{year}' number='{i-1}'> ")                             #I want each volume clearly assigned to the year it was extracted from and therefore add this attribute

for num, line in enumerate(text, 0):
    
    volume_score = fuzz.ratio(volume, line)   
         
    if volume_score >= 70:
        volume_text.append(line)
        volume_text.append("</volume>\n")
        volume_text.append(f"<volume year='{year}' number='{i}'> ") 
        
        i += 1
    else: 
        volume_text.append(line)

volume_text.append("</volume>")

#volume_text[0:730]
#volume_text[7000:len(volume_text)]        

In [16]:
#First I separate the yearly texts by its volumnes and continue working with smaller sections.
#I identify the volume beginning and end points and write these into lists.

start_num = []
end_num = []

for num, line in enumerate(volume_text, 0):
    if line.startswith(f"<volume year='{year}' number="):
        start_num.append(num) 
    if line.startswith("</volume>"):
        end_num.append(num+1)                                    #because counting starts at 0 and I want to add the detected line to the document, I add 1.
        
print(start_num, end_num) 

[0, 735, 1351, 1985, 2785, 3394, 4036, 4699, 5324, 5978, 6598, 7287, 7963] [735, 1351, 1985, 2785, 3394, 4036, 4699, 5324, 5978, 6598, 7287, 7963, 7965]


In [17]:
#I write each of the volumes into a separate document 

i = 0

for i in range(0,len(start_num)):                                      #I go through the range of one of the lists 
    new_text = []                                                      #The new_text list is set back to nothing after each document written 
      
    for num, line in enumerate(volume_text,0):                         #I go through each line of the volume annotated list 

        if num in range(start_num[i], end_num[i]):                     #If it is within the range of the i-element of each of the two lists
            new_text.append(line)                                      #I write the line into the new_text list  
        else:                                                          #If it is not within the range I want to extract
            continue                                                   #I skipp these lines and continue with the code
    
    out_filename = f'Output/NVR/{year}/{year}_V{i}_NVR_Ano.txt'        #I give the output directory  
    filepath = Path(out_filename)                                      #I get the path of the filename
    filepath.parent.mkdir(parents=True, exist_ok=True)                 #If there is no folder yet it gets created

    with open(out_filename, 'x') as fp:                                #A file is created
        fp.write("".join(str(item) for item in new_text))              #The new_text elements are written in the file joined with now separator (\n included in the original lines) 
        
    i += 1                                                             #I go to the next set of elements in the lists  
    
#I check each of the created documents manually to make sure no volume is missed.             

#### Annotating sections within volumes

- 1870_V4_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 8f, because there is now signifier that I could detect that marks the beginning of the given lecture.
- 1870_V5_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 6f, because there is now signifier that I could detect that marks the beginning of the given lecture.
- 1870_V10_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 516f, because there is now signifier that I could detect that marks the beginning of the given text.
- 1870_V11_NVR_Ano_New.txt: I manually exclude the detected metro_list and observer_list sections because here they are part of the yearly report.
- 1872_V0_NVR_Ano_New.txt: I manually exclude the detected observer_list section because here it was part of a monthly meeting.
- 1872_V2_NVR_Ano_New.txt: I manually exclude the detected observer_list section because here it is part of the yearly report.
- 1872_V2_NVR_Ano.txt: I manually remove the line breaks from "Verzeichniss der Gesellschaften, wissenschaftlichen Anstalten etc." in line 710, so I can detect it as the beginning of a section.
- 1872_V7_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 17f, because there is now signifier that I could detect that marks the beginning of the given text.
- 1872_V11_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 753f, to seperate the "Anzeige" from the preceding new_mem_list.
- 1874_V3_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 619f, to seperate the list of exchanging societies from the rest of the yearly report.
- 1874_V5_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 6f, to mark the beginning of the text session of the annual meeting.
- 1874_V6_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='list'>" in line 398f, to correctly mark the end of the new_mem_list.
- 1874_V8_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 18f, to mark the beginning of the given lecture.
- 1874_V9_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 422f, to correctly mark the end of the new_mem_list.
- 1875_V0_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 112f, to correctly mark the beginning of the lecture.
- 1875_V0_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='list'>" in line 718f, to correctly mark the end of the new_mem_list.
- 1875_V1_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 6f, to correctly mark the beginning of the lecture.
- 1875_V4_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 18f, to correctly mark the beginning of the lecture.
- 1875_V5_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 6f, to correctly mark the beginning of the lecture.
- 1875_V6_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 19f, to correctly mark the beginning of the lecture.
- 1875_V7_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 19f, to correctly mark the beginning of the lecture.
- 1875_V7_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='table'>" in line 519f, to correctly mark the end of the new_mem_list.
- 1875_V9_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 5f, to correctly mark the beginning of the lecture.
- 1875_V10_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='list'>" in line 612f, to correctly mark the end of the new_mem_list.
- 1877_V2_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 10f, to correctly mark the beginning of the lecture.
- 1877_V3_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 22f, to correctly mark the beginning of the lecture.
- 1877_V6_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 640f, to correctly mark the end of the new_mem_list.
- 1877_V9_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 23f, to correctly mark the beginning of the lecture.
- 1880_V1_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='monthlymeet'>" in line 12f, to correctly mark the beginning of the monthly meetings.
- 1880_V3_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='monthlymeet'>" in line 24f, to correctly mark the beginning of the monthly meetings.
- 1880_V5_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 28f, to correctly mark the beginning of the lecture.
- 1880_V8_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 18f, to correctly mark the beginning of the lecture.
- 1880_V9_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 16f, to correctly mark the beginning of the lecture.
- 1880_V11_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 17f, to correctly mark the beginning of the lecture.

In [ ]:
#Im gonna read in the volumes separately to get a better overview 

year = '1880'
volume_nr = 12
filename = f'Output/NVR/{year}/{year}_V{volume_nr}_NVR_Ano.txt'
with open(filename, 'r') as fp:
    text = fp.readlines()

In [ ]:
#These are roughly the same as early but can be adjusted depending on the contents of each volume 

volume = 'Druck von W. F. Häcker in Riga.'                 
register = 'Inhaltsverzeichniss. '
meetings =  'Sitzungsberichte. '                                                                #'Sitzungen des Vereins.'
prints_list = 'Eingegangene Schriften.'
new_mem_list =  'Mitglieder. \n'                                                                #'Neuaufgenommene Mitglieder.'
mem_list =  'Verzeichniss der Mitglieder '
soc_list = 'Wissenschaftliche Vereine und Institute, mit welchen der Natur-\n'
metro_list = 'Meteorologische Station Riga.'                                                    #'Eingegangene meteorologische Beobachtungen. '
observer_table = 'Station Riga. Monat Januar 1873.'                                             #"Meteorologische Beobachtungen in Riga (N.Br. 56° 5?')."
observer_list = "Phänologische Beobachtungen"
yearly_report = "30ster Jahresbericht"

In [ ]:
for num, line in enumerate(text, 1):
                                
    volume_score = fuzz.ratio(volume, line)  
    register_score = fuzz.ratio(register, line)
    meetings_score = fuzz.ratio(meetings, line)
    prints_list_score = fuzz.ratio(prints_list, line)
    new_mem_list_score = fuzz.ratio(new_mem_list, line)
    mem_list_score = fuzz.ratio(mem_list, line)
    soc_list_score = fuzz.ratio(soc_list, line)
    metro_list_score = fuzz.ratio(metro_list, line)
    observer_table_score = fuzz.ratio(observer_table, line)
    observer_list_score = fuzz.ratio(observer_list, line) 
    yearly_report_score = fuzz.ratio(yearly_report, line)
     
    if volume_score >= 70:                                                              
        print(f"Volume: {line}; Score: {volume_score}; in Line: {num}")
    elif register_score >= 70:                                                             
        print(f"Register: {line}; Score: {register_score}; in Line: {num}")
    elif meetings_score >= 70:                                                             
        print(f"Meetings: {line}; Score: {meetings_score}; in Line: {num}")
    elif prints_list_score >= 70:                                                           
        print(f"Prints: {line}; Score: {prints_list_score}; in Line: {num}")
    elif new_mem_list_score >= 70:                                                         
        print(f"Members List: {line}; Score: {new_mem_list_score}; in Line: {num}")
    elif mem_list_score >= 70:                                                         
        print(f"Members List: {line}; Score: {mem_list_score}; in Line: {num}")
    elif soc_list_score >= 70:                                                         
        print(f"Societies List: {line}; Score: {soc_list_score}; in Line: {num}")
    elif metro_list_score >= 70:                                                          
        print(f"Meteorological list: {line}; Score: {metro_list_score}; in Line: {num}")
    elif observer_table_score >= 70:                                                        
        print(f"Meteorological observations: {line}; Score: {observer_table_score}; in Line: {num}")
    elif observer_list_score >= 70:                                                    
        print(f"Phenological observations: {line}; Score: {observer_list_score}; in Line: {num}")
    elif yearly_report_score >= 70:                                      
        print(f"Yearly report: {line}; Score: {yearly_report_score}; in Line: {num}") 

In [ ]:
#I now have to find and annotate the sections of each volume 
#These vary significantly and therefore have to be checked manually 

new_text = []

for num, line in enumerate(text, 0):

    meetings_score = fuzz.ratio(meetings, line)
    register_score = fuzz.ratio(register, line)
    prints_list_score = fuzz.ratio(prints_list, line)
    new_mem_list_score = fuzz.ratio(new_mem_list, line)
    mem_list_score = fuzz.ratio(mem_list, line)
    soc_list_score = fuzz.ratio(soc_list, line)
    metro_list_score = fuzz.ratio(metro_list, line)
    observer_table_score = fuzz.ratio(observer_table, line)
    observer_list_score = fuzz.ratio(observer_list, line) 
    yearly_report_score = fuzz.ratio(yearly_report, line)
     
    if line.startswith(f"<volume year='{year}' number="):
        new_text.append(line)
        new_text.append("<section type='beginning'> ")
        
    elif register_score >= 70:
        new_text.append("</section>\n")
        ano_line = f"<section type='register'> {line}"
        new_text.append(ano_line)    
    
    elif meetings_score >= 90:
        new_text.append("</section>\n")
        ano_line = f"<section type='monthlymeet'> {line}"
        new_text.append(ano_line)

    elif prints_list_score >= 70:
        new_text.append("</section>\n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)

    elif new_mem_list_score >= 70: 
        new_text.append("</section>\n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)
        
    elif mem_list_score >= 70: 
        new_text.append("</section>\n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)
        
    elif soc_list_score >= 70: 
        new_text.append("</section>\n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)

    elif metro_list_score >= 70:
        new_text.append("</section>\n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)

    elif observer_table_score >= 70:    
        new_text.append("</section>\n")
        ano_line = f"<section type='table'> {line}"
        new_text.append(ano_line)

    elif observer_list_score >= 70: 
        new_text.append("</section>\n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)

    elif yearly_report_score >= 70:  
        new_text.append("</section>\n")
        ano_line = f"<section type='yearlymeet'> {line}"
        new_text.append(ano_line)
    
    elif line.startswith(f"</volume>"):
        new_text.append("</section>\n")
        new_text.append(line)
        
    else:
        new_text.append(line)

In [ ]:
#I check wether everything was annotated correctly 
new_text

In [ ]:
#I write the new annotated list into a .txt file 

out_filename = f'Output/NVR/{year}/{year}_V{volume_nr}_NVR_Ano_New.txt'                      

filepath = Path(out_filename)                             
filepath.parent.mkdir(parents=True, exist_ok=True)                       #creates the folders if they don't exist yet

with open(out_filename, 'x') as fp:                                      #"x" to not overwrite already existing files by accident
    fp.write("".join(str(item) for item in new_text))

### Annotating sections within volumes 

- 1870_V4_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 8f, because there is now signifier that I could detect that marks the beginning of the given lecture.
- 1870_V5_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 6f, because there is now signifier that I could detect that marks the beginning of the given lecture.
- 1870_V10_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 516f, because there is now signifier that I could detect that marks the beginning of the given text.
- 1870_V11_NVR_Ano_New.txt: I manually exclude the detected metro_list and observer_list sections because here they are part of the yearly report. 
- 1872_V0_NVR_Ano_New.txt: I manually exclude the detected observer_list section because here it was part of a monthly meeting.
- 1872_V2_NVR_Ano_New.txt: I manually exclude the detected observer_list section because here it is part of the yearly report.
- 1872_V2_NVR_Ano.txt: I manually remove the line breaks from "Verzeichniss der Gesellschaften, wissenschaftlichen Anstalten etc." in line 710, so I can detect it as the beginning of a section. 
- 1872_V7_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 17f, because there is now signifier that I could detect that marks the beginning of the given text.
- 1872_V11_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 753f, to seperate the "Anzeige" from the preceding new_mem_list. 
- 1874_V3_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 619f, to seperate the list of exchanging societies from the rest of the yearly report. 
- 1874_V5_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 6f, to mark the beginning of the text session of the annual meeting.
- 1874_V6_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='list'>" in line 398f, to correctly mark the end of the new_mem_list. 
- 1874_V8_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 18f, to mark the beginning of the given lecture. 
- 1874_V9_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 422f, to correctly mark the end of the new_mem_list.
- 1875_V0_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 112f, to correctly mark the beginning of the lecture.
- 1875_V0_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='list'>" in line 718f, to correctly mark the end of the new_mem_list.
- 1875_V1_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 6f, to correctly mark the beginning of the lecture.
- 1875_V4_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 18f, to correctly mark the beginning of the lecture.
- 1875_V5_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 6f, to correctly mark the beginning of the lecture.
- 1875_V6_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 19f, to correctly mark the beginning of the lecture.
- 1875_V7_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 19f, to correctly mark the beginning of the lecture.
- 1875_V7_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='table'>" in line 519f, to correctly mark the end of the new_mem_list.
- 1875_V9_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 5f, to correctly mark the beginning of the lecture.
- 1875_V10_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='list'>" in line 612f, to correctly mark the end of the new_mem_list.
- 1877_V2_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 10f, to correctly mark the beginning of the lecture.
- 1877_V3_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 22f, to correctly mark the beginning of the lecture.
- 1877_V6_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 640f, to correctly mark the end of the new_mem_list.
- 1877_V9_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 23f, to correctly mark the beginning of the lecture.
- 1880_V1_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='monthlymeet'>" in line 12f, to correctly mark the beginning of the monthly meetings.
- 1880_V3_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='monthlymeet'>" in line 24f, to correctly mark the beginning of the monthly meetings.
- 1880_V5_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 28f, to correctly mark the beginning of the lecture.
- 1880_V8_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 18f, to correctly mark the beginning of the lecture.
- 1880_V9_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 16f, to correctly mark the beginning of the lecture.
- 1880_V11_NVR_Ano_New.txt: I manually add a "\</section>\n" and a "\<section type='text'>" in line 17f, to correctly mark the beginning of the lecture.

In [279]:
#Im gonna read in the volumes separately to get a better overview 

year = '1880'
volume_nr = 12
filename = f'Output/NVR/{year}/{year}_V{volume_nr}_NVR_Ano.txt'
with open(filename, 'r') as fp:
    text = fp.readlines()

In [280]:
#These are roughly the same as early but can be adjusted depending on the contents of each volume 

volume = 'Druck von W. F. Häcker in Riga.'                 
register = 'Inhaltsverzeichniss. '
meetings =  'Sitzungsberichte. '                                                                #'Sitzungen des Vereins.'
prints_list = 'Eingegangene Schriften.'
new_mem_list =  'Mitglieder. \n'                                                                #'Neuaufgenommene Mitglieder.'
mem_list =  'Verzeichniss der Mitglieder '
soc_list = 'Wissenschaftliche Vereine und Institute, mit welchen der Natur-\n'
metro_list = 'Meteorologische Station Riga.'                                                    #'Eingegangene meteorologische Beobachtungen. '
observer_table = 'Station Riga. Monat Januar 1873.'                                             #"Meteorologische Beobachtungen in Riga (N.Br. 56° 5?')."
observer_list = "Phänologische Beobachtungen"
yearly_report = "30ster Jahresbericht"

In [281]:
for num, line in enumerate(text, 1):
                                
    volume_score = fuzz.ratio(volume, line)  
    register_score = fuzz.ratio(register, line)
    meetings_score = fuzz.ratio(meetings, line)
    prints_list_score = fuzz.ratio(prints_list, line)
    new_mem_list_score = fuzz.ratio(new_mem_list, line)
    mem_list_score = fuzz.ratio(mem_list, line)
    soc_list_score = fuzz.ratio(soc_list, line)
    metro_list_score = fuzz.ratio(metro_list, line)
    observer_table_score = fuzz.ratio(observer_table, line)
    observer_list_score = fuzz.ratio(observer_list, line) 
    yearly_report_score = fuzz.ratio(yearly_report, line)
     
    if volume_score >= 70:                                                              
        print(f"Volume: {line}; Score: {volume_score}; in Line: {num}")
    elif register_score >= 70:                                                             
        print(f"Register: {line}; Score: {register_score}; in Line: {num}")
    elif meetings_score >= 70:                                                             
        print(f"Meetings: {line}; Score: {meetings_score}; in Line: {num}")
    elif prints_list_score >= 70:                                                           
        print(f"Prints: {line}; Score: {prints_list_score}; in Line: {num}")
    elif new_mem_list_score >= 70:                                                         
        print(f"Members List: {line}; Score: {new_mem_list_score}; in Line: {num}")
    elif mem_list_score >= 70:                                                         
        print(f"Members List: {line}; Score: {mem_list_score}; in Line: {num}")
    elif soc_list_score >= 70:                                                         
        print(f"Societies List: {line}; Score: {soc_list_score}; in Line: {num}")
    elif metro_list_score >= 70:                                                          
        print(f"Meteorological list: {line}; Score: {metro_list_score}; in Line: {num}")
    elif observer_table_score >= 70:                                                        
        print(f"Meteorological observations: {line}; Score: {observer_table_score}; in Line: {num}")
    elif observer_list_score >= 70:                                                    
        print(f"Phenological observations: {line}; Score: {observer_list_score}; in Line: {num}")
    elif yearly_report_score >= 70:                                      
        print(f"Yearly report: {line}; Score: {yearly_report_score}; in Line: {num}")        

In [282]:
#I now have to find and annotate the sections of each volume 
#These vary significantly and therefore have to be checked manually 

new_text = []

for num, line in enumerate(text, 0):

    meetings_score = fuzz.ratio(meetings, line)
    register_score = fuzz.ratio(register, line)
    prints_list_score = fuzz.ratio(prints_list, line)
    new_mem_list_score = fuzz.ratio(new_mem_list, line)
    mem_list_score = fuzz.ratio(mem_list, line)
    soc_list_score = fuzz.ratio(soc_list, line)
    metro_list_score = fuzz.ratio(metro_list, line)
    observer_table_score = fuzz.ratio(observer_table, line)
    observer_list_score = fuzz.ratio(observer_list, line) 
    yearly_report_score = fuzz.ratio(yearly_report, line)
     
    if line.startswith(f"<volume year='{year}' number="):
        new_text.append(line)
        new_text.append("<section type='beginning'> ")
        
    elif register_score >= 70:
        new_text.append("</section>\n")
        ano_line = f"<section type='register'> {line}"
        new_text.append(ano_line)    
    
    elif meetings_score >= 90:
        new_text.append("</section>\n")
        ano_line = f"<section type='monthlymeet'> {line}"
        new_text.append(ano_line)

    elif prints_list_score >= 70:
        new_text.append("</section>\n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)

    elif new_mem_list_score >= 70: 
        new_text.append("</section>\n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)
        
    elif mem_list_score >= 70: 
        new_text.append("</section>\n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)
        
    elif soc_list_score >= 70: 
        new_text.append("</section>\n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)

    elif metro_list_score >= 70:
        new_text.append("</section>\n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)

    elif observer_table_score >= 70:    
        new_text.append("</section>\n")
        ano_line = f"<section type='table'> {line}"
        new_text.append(ano_line)

    elif observer_list_score >= 70: 
        new_text.append("</section>\n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)

    elif yearly_report_score >= 70:  
        new_text.append("</section>\n")
        ano_line = f"<section type='yearlymeet'> {line}"
        new_text.append(ano_line)
    
    elif line.startswith(f"</volume>"):
        new_text.append("</section>\n")
        new_text.append(line)
        
    else:
        new_text.append(line)

In [283]:
#I check wether everything was annotated correctly 
new_text

["<volume year='1880' number='13'> III   DDDaaatttuuummm   nnneeeuuueeennn   SSStttyyylllsss...   \n",
 "<section type='beginning'> ",
 'Barometer. \n',
 'Still. Haarhygr. \n',
 'Wind. \n',
 'NNE. \n',
 'Bewölkung. \n',
 'ESE. Maxim. \n',
 'Minim. \n',
 'SSW. \n',
 'RReeggeenn  ooddeerr  SScchhnneeee..  \n',
 'SW. \n',
 'NNiieeddeerrsscchhllaagg..  \n',
 'NW. \n',
 'Dünamünde. \n',
 '1 \n',
 '</section>\n',
 '</volume>']

In [284]:
#I write the new annotated list into a .txt file 

out_filename = f'Output/NVR/{year}/{year}_V{volume_nr}_NVR_Ano_New.txt'                      

filepath = Path(out_filename)                             
filepath.parent.mkdir(parents=True, exist_ok=True)                       #creates the folders if they don't exist yet

with open(out_filename, 'x') as fp:                                      #"x" to not overwrite already existing files by accident
    fp.write("".join(str(item) for item in new_text))

### Year 1881-1924 
These materials are not separated in volumes. 

##### manual changes

- In file 1881_NVR_New.txt I manually add a line break after "Sitzungsberichte." in line 1184.
- In file 1882_NVR_Ano.txt I manually add a "\</section>\n" and a "\<section type='text'>" in line 2378f, because there is a scientific text only marked by its title after the memberslist, which I cannot detect by any pattern. 
- In file 1884_NVR_New.txt I manually add a line break after "Sitzungsberichte." in line 573.
- NB: In file 1884_NVR_Ano.txt there is no Membership list. 
- In file 1885_NVR_New.txt I manually add a line break after "Sitzungsberichte." in line 290.
- NB: In file 1886_NVR_Ano.txt there is no Membership list.
- NB: In file 1888_NVR_Ano.txt there is no Membership list.
- NB: In file 1890_NVR_Ano.txt there is no Membership list.
- NB: In file 1892_NVR_Ano.txt there is no Membership list.
- In file 1893_NVR_Ano.txt I manually add a "\</section>\n" and a "\<section type='list'> " in line 595f.
- NB: In file 1894_NVR_Ano.txt there is no Membership list. Second station in Ustj-Dwinsk. !!!
- NB: In file 1895_NVR_Ano.txt there is no Membership list. 
- NB: In file 1897_NVR_Ano.txt the monthly meetings are marked separately, because they were long enough to identify directly. 
- NB: file 1897_NVR_New/Cor_40.txt and 1898_NVR_New/Cor_41.txt actually contain the same text. I will rename the newly created 1897_NVR_Ano.txt manually into 1898_NVR_Ano.txt and continue working with that one, skipping the 1898_NVR_New completely. 
- NB: In file 1900_NVR_Ano.txt there is no Membership list.
- NB: In file 1907_NVR_Ano.txt there is no Membership list. Second station in Dünamünde. 
- NB: In file 1915_NVR_Ano.txt there is no Membership list. 
- NB: In file 1924_NVR_Ano.txt membership list included in yearly report. 

##### code

In [5]:
#I read the file into a list 

year = '1872'
filename = f'Sources/NVR/{year}_NVR_New.txt'
with open(filename, 'r') as fp:
    text = fp.readlines()
    

In [8]:
#I adjust the comparison lines here so I only need to make adjustments here and not in the checking and annotating sections separately
#This is worked before because there were few changes to be made and few elements to detected
#But considereing the volume I extracted them out. 
                  
meetings = '500. ordentl. Versammlung am 17. (4.) Sept. 1872.'
pubex_list = 'Wissenschaftliche Vereine und Anstalten, '
#prints_list = 'Eingegangene Schriften.'
board_list = 'Direktorium des Naturforscher-Vereins zu Riga'
mem_list = 'Verzeichnis der IRifgiieder.' 
#new_mem_list = 'Neuaufgenommene Mitglieder.'
meteor_stations = 'Die meteorologischen Stationen ties Naturforscher-'
#meteor_list = 'Eingegangene meteorologische Beobachtungen. '
meteor_observer_r_table = "Station Riga. Monat Juni 1879."
meteor_observer_d_table = 'Station Dünamünde. Monat Mai 1880.'
#observer_list = "Phänologisohe Beobachtungen "
yearly_report = "Bericht über die Tätigkeit des Vereins in der Zeit" #"-9-Der nafurforscfter*Verein zu Riga" #"57. Jahresbericht vom 1. Juli 1901 bis zum 1. Juli 1902."  #"53. Jahresbericht des Naturforscher-Vereins zu Riga"

In [9]:
#I check what sections are being detected. 
#I try to adjust the parameters as best as possible to capture all sections.
#If I do notice missing sections I have to check the file and manually adapt the lines if needed.

for num, line in enumerate(text, 1):
                                                                  
    meetings_score = fuzz.ratio(meetings, line)
    pubex_list_score = fuzz.ratio(pubex_list, line)
    #prints_list_score = fuzz.ratio(prints_list, line)
    board_list_score = fuzz.ratio(board_list, line)
    mem_list_score = fuzz.ratio(mem_list, line)
    #new_mem_list_score = fuzz.ratio(new_mem_list, line)
    meteor_stations_score = fuzz.ratio(meteor_stations, line)
    #meteor_list_score = fuzz.ratio(meteor_list, line)
    meteor_observer_r_table_score = fuzz.ratio(meteor_observer_r_table, line)
    meteor_observer_d_table_score = fuzz.ratio(meteor_observer_d_table, line)
    #observer_list_score = fuzz.ratio(observer_list, line) 
    yearly_report_score = fuzz.ratio(yearly_report, line)
     
    
    if meetings_score >= 60:                                                             
        print(f"Meetings: {line}; Score: {meetings_score}; in Line: {num}")
    elif pubex_list_score >= 90:                                                         
        print(f"Publication Exchange: {line}; Score: {pubex_list_score}; in Line: {num}")    
    #elif prints_list_score >= 70:                                                           
        #print(f"Prints: {line}; Score: {prints_list_score}; in Line: {num}")
    elif board_list_score >= 85:                                                         
        print(f"Board List: {line}; Score: {board_list_score}; in Line: {num}")
    elif mem_list_score >= 80:                                                         
        print(f"Members List: {line}; Score: {mem_list_score}; in Line: {num}")
    elif meteor_stations_score >= 80:                                                         
        print(f"Meteorlogical Stations: {line}; Score: {meteor_stations_score}; in Line: {num}")
    #elif meteor_list_score >= 70:                                                          
        #print(f"Meteorological list: {line}; Score: {meteor_list_score}; in Line: {num}")
    elif meteor_observer_r_table_score >= 70:                                                        
        print(f"Meteorological observations: {line}; Score: {meteor_observer_r_table_score}; in Line: {num}")
    elif meteor_observer_d_table_score >= 70:                                                        
        print(f"Meteorological observations: {line}; Score: {meteor_observer_d_table_score}; in Line: {num}")
    #elif observer_list_score >= 75:                                                    
        #print(f"Phenological observations: {line}; Score: {observer_list_score}; in Line: {num}")
    elif yearly_report_score >= 85:                                      
        print(f"Yearly report: {line}; Score: {yearly_report_score}; in Line: {num}")   
       

Meetings: Sitzungen des Vereins. 
; Score: 93; in Line: 172
Meetings: Sitzungen des Vereins. 
; Score: 93; in Line: 835
Members List: Verzeichniss der Mitglieder 
; Score: 81; in Line: 1907
Meetings: Sitzungen des Vereins. 
; Score: 93; in Line: 2531
Meetings: Sitzungen des Vereins. 
; Score: 93; in Line: 3194
Meetings: Sitzungen des Vereins. 
; Score: 93; in Line: 3871
Meetings: Sitzungen des Vereins. 
; Score: 93; in Line: 4520
Meetings: Sitzungen des Vereins. 
; Score: 93; in Line: 5894
Meetings: Sitzungen des Vereins. 
; Score: 93; in Line: 6846
Meetings: Sitzungen des Vereins. 
; Score: 93; in Line: 7695


In [210]:
text[0:60]

['Kormptazlilat! \n',
 'des \n',
 'N aturforscher -V ereins \n',
 'zu Riga. \n',
 'Redigiert von R. Meyer und A. Meder, \n',
 'LVIIL \n',
 '(Dieser Band enthält VI -f- 122 Seiten, 1 Tafel und 32 besonders paginierte \n',
 'Seiten mit meteorologischen Tabellen.) \n',
 'Riga, 1924, \n',
 'Druck von W, F, Häcker, \n',
 'Inhalt. \n',
 'Inhalt der Sitzungsberichte III \n',
 'Zum Geleit VI \n',
 'Dr. med. Otto Thilo f. (Von B. Taube.) 1 \n',
 'Professor Dr. Bruno Dossf und seine Verdienste um die \n',
 'Durchforschung des ostbaltischen Gebiets. (Von K. R. Kupffer.) 3 \n',
 'Dr. med. Karl von L u t z a u f. (Von K. R. Kupffer.) .... 7 \n',
 'Der Naturforscher-Verein zu Riga in den Jahren \n',
 '1895—1920. Vom Vereinssekretär 9 \n',
 'Sitzungsberichte 30 \n',
 'Bericht über die Tätigkeit des Vereius in der Zeit vom 1. Juli 1914 \n',
 'bis zum 30. Juni 1923. 63 \n',
 'W. M. Fischer: Über die Bildung Liesegangscher Schichtungen ... 82> \n',
 'Max Stoll: Die Mäuseplage und der Wildsegen im Jahre 

In [217]:
#I identify the sections and insert the section tags 
new_text = []
new_text.append("<section type='beginning'>")

for num, line in enumerate(text, 0): 
        
    meetings_score = fuzz.ratio(meetings, line)
    pubex_list_score = fuzz.ratio(pubex_list, line)
    #prints_list_score = fuzz.ratio(prints_list, line)
    board_list_score = fuzz.ratio(board_list, line)
    mem_list_score = fuzz.ratio(mem_list, line)
    #new_mem_list_score = fuzz.ratio(new_mem_list, line)
    meteor_stations_score = fuzz.ratio(meteor_stations, line)
    #meteor_list_score = fuzz.ratio(meteor_list, line)
    meteor_observer_r_table_score = fuzz.ratio(meteor_observer_r_table, line)
    meteor_observer_d_table_score = fuzz.ratio(meteor_observer_d_table, line)
    #observer_list_score = fuzz.ratio(observer_list, line) 
    yearly_report_score = fuzz.ratio(yearly_report, line)
     
        
    if meetings_score >= 60:
        new_text.append("</section>\n")
        ano_line = f"<section type='monthlymeet'> {line}"
        new_text.append(ano_line)

    elif pubex_list_score >= 90:
        new_text.append("</section>\n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)

    elif board_list_score >= 85: 
        new_text.append("</section>\n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)
        
    elif mem_list_score >= 80: 
        new_text.append("</section>\n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)

    elif meteor_stations_score >= 80:
        new_text.append("</section>\n")
        ano_line = f"<section type='list'> {line}"
        new_text.append(ano_line)

    elif meteor_observer_r_table_score >= 70:    
        new_text.append("</section>\n")
        ano_line = f"<section type='table'> {line}"
        new_text.append(ano_line)
    
    elif meteor_observer_d_table_score >= 70:    
        new_text.append("</section>\n")
        ano_line = f"<section type='table'> {line}"
        new_text.append(ano_line)

    elif yearly_report_score >= 85:  
        new_text.append("</section>\n")
        ano_line = f"<section type='yearlymeet'> {line}"
        new_text.append(ano_line)
        
    else:
        new_text.append(line)
    
new_text.append("</section>")

In [218]:
#new_text[100:1800]

In [219]:
#I write the new annotated list into a .txt file 

out_filename = f'Output/NVR/{year}_NVR_Ano.txt'                        

filepath = Path(out_filename)                             
filepath.parent.mkdir(parents=True, exist_ok=True)                       #creates the folders if they don't exist yet

with open(out_filename, 'x') as fp:                                      #"x" to not overwrite already existing files by accident
    fp.write("".join(str(item) for item in new_text))

### Isolating and annotating membership lists

In [108]:
#I read the file into a list
year = "1924"
#volume_nr = 4
filename = f'Output/NVR/{year}_NVR_Ano.txt'
with open(filename, 'r') as fp:
    text = fp.readlines()

In [110]:
#I look for the section markers and write them in lists
#Same as GEG

sections_s = []
sections_e = []

for num, line in enumerate(text, 0):
    if line.startswith("<section type='yearlymeet'>"):                           #Only section beginnings with marker "list".
        sections_s.append(num)
        
for num, line in enumerate(text, 1):        
    if line == "</section>\n":                                            #All section endings are the same.
        sections_e.append(num)
        
print(sections_s)
print(sections_e)

[3553]
[1835, 1870, 1879, 1890, 1897, 1903, 1935, 1980, 2028, 2049, 2083, 2153, 2189, 2214, 2223, 2230, 2255, 2271, 2299, 2303, 2357, 2374, 2396, 2404, 2438, 2442, 2446, 2453, 2493, 2525, 2587, 2599, 2628, 2642, 2661, 2669, 2701, 2714, 2735, 2744, 2757, 2766, 2770, 2788, 2795, 2800, 2804, 2829, 2834, 2838, 2876, 2924, 2984, 2988, 3025, 3034, 3040, 3063, 3160, 3172, 3181, 3186, 3193, 3256, 3263, 3349, 3370, 3376, 3387, 3398, 3453, 3467, 3506, 3510, 3523, 3540, 3548, 3553, 6637, 6763, 6902, 7039, 7179, 7250, 7307, 7439, 7573, 7701, 7835, 7977, 8127]


In [115]:
#I check which of the list sections is the membership list and create a list only with this section
#Same as GEG
members_text = text[sections_s[0]:sections_e[-13]]
members_text

["<section type='yearlymeet'> Bericht über die Tätigkeit des Vereins in der Zeit \n",
 'Dom 1. 3uli 1914 bis zum 30. 3uni 1923. \n',
 'fl. Vereinsangehörige. \n',
 'Es verstarben in der Zeit vom 1. Juli 1914 bis zum Herbst 1917: \n',
 'Gymnasialdirektor a. D. G. S c h w e d e r (ord. Mitgl. seit 1861, \n',
 'Ehrenmitgl. seit 1887, Vorstandsglied seit 1862, Redakteur des Korr.-Bl. \n',
 'seit 1873, Museumsdirektor seit 1895, Sekretär 1862—73, Vizepräses \n',
 '1873—75, Präses 1875—1913, Ehrenpräses seit 1910), Prof. Dr. E. Mach \n',
 'in Wien (E.-M. 1895)*), Wirkl. Staatsrat Prof. Dr. A. Wojeikow \n',
 '(B.-M. 1895), Oberlehrer A. Werner (1876j E.-M. 1902, Vorstandsglied \n',
 'seit 1878, Direktor der meteor. Stationen seit 1880), Oberlehrer K. G r e v 6 \n',
 '(k. M. 1892), Oberlehrer E. Preymann (1906), Fabrikdirektor R. Geist \n',
 '(1893), Notarius S. Kiersnowsky (1895), Dr. med. G. v. Knorre \n',
 '(1895), Mag. pharm. F. Ludwig (1898, Vorstandsglied seit 1907, Schatz\xad\n',
 'meis

In [101]:
#Alsmost the same as GEG 
#adapting the comparison strings for HM, CM, and OM
#adding the additional marker constant member ConM

#First round annotating the membership list
#I again use XML inspired tags to mark the structuring elements of the list.
#This is the first level of information including the status of their membership: honorable, ordinary or corresponding.
#Depending on the quality of the OCR these reference words need to be adapted.

members_ano_1 = []
for line in members_text: 
    hon_mem = fuzz.ratio("A. Ehrenmitglieder. ", line) 
    con_mem = fuzz.ratio("B. Beständige Mitglieder. ", line)
    ord_mem = fuzz.ratio("C. Ordentliche Mitglieder. ", line) 
    cor_mem = fuzz.ratio("D. Correspondirende Mitglieder. \n", line) 
    
    if hon_mem >= 80:
        members_ano_1.append("<members>")                                          #I open members section
        members_ano_1.append(f"<honorable_members> {line}")                        #I open honorable members section
        print("HM detected")
        
    elif cor_mem >=80:
        members_ano_1.append("</honorable_members>")
        #members_ano_1.append("</ordinary_members>")
        members_ano_1.append(f"<corresponding_members> {line}")                    #I open corresponding members section
        print("CM detected")
        
    #elif con_mem >= 80:
        #members_ano_1.append("</corresponding_members>")
        #members_ano_1.append("</honorable_members>")                               #I close honorable members section
        #members_ano_1.append(f"<constant_members> {line}")                         #I open ordinary members section
        #print("ConM detected")     
        
    elif ord_mem >= 80:
        #members_ano_1.append("</honorable_members>")                               #I close honorable members section
        #members_ano_1.append("</constant_members>")  
        members_ano_1.append("</corresponding_members>")
        members_ano_1.append(f"<ordinary_members> {line}")                         #I open ordinary members section
        print("OM detected") 
        
    
    elif line == "</section>\n":
        #members_ano_1.append("</corresponding_members>")                           #I close corresponding members section
        members_ano_1.append("</ordinary_members>")
        members_ano_1.append("</members>")                                         #I close members section
        members_ano_1.append(line)
        print("Section tag detected")
    
    else:                                                                          #Don't forget to also append the rest of the original list
        members_ano_1.append(line)
        
members_ano_1

HM detected
CM detected
OM detected
Section tag detected


["<section type='list'> Verzeichnis der ülitglieder. \n",
 '<members>',
 '<honorable_members> I. Ehrenmitglieder. \n',
 '. Dr. G. Schweinfurth in Berlin seit (1867) 1872 \n',
 '. G. Schweder, Staatsrat, in Riga, Peter-Paulstrasse 2 „ (1861) 1887 \n',
 '. Dr. 0. Drude, Geh. Hofrat, Professor, in Dresden „ 1895 \n',
 '. Dr. A. Jentzsch, Professor, Geh. Bergrat, in Berlin „ 1895 \n',
 '. Dr. E. Mach, Professor, in Wien „ 1895 \n',
 '. Dr. A. v. Oettingen, Wirkl. Staatsrat, Professor, in Leipzig ... „ (1870) 1895 \n',
 '. Dr. W. Ostwald, Geheimrat, Professor, in Leipzig „ 1895 \n',
 '. Dr. L. Stieda, Geh. Medizinalrat, Professor, in Königsberg . . „ (1870) 1895 \n',
 '. Dr. A. Wojeikow, Wirkl. Staatsrat, Professor, in St. Petersburg . „ 1895 \n',
 '. M. Rykatschew, Gen.-Maj., Dir. d. Nikolai-Obs., in St. Petersburg „ 1899 \n',
 '. A. Werner, Oberlehrer, Dir. d. meteorol. Stat., Riga, Gertrudstrasse 35 „ (1876) 1902 \n',
 '. Dr. J. Borodin, Geheimrat, Akademiker, in St. Petersburg ... „ (19

In [102]:
#I determine where the first level structural elements start and end, 
#because I want the lower levels to reference the parent in order to avoid a duplicate in a marker opener.

for num, line in enumerate(members_ano_1, 0):
    if line.startswith("<honorable_members>"):                    #The opening marker gives the number for the starting point of the iteration of the list.
        start_hm = num
    if line == "</honorable_members>":                            #The closing marker gives the number for the end point of the iteration of the list.
        end_hm = num +1                                           #I add 1 because I want the closing line itself also included in the iterated section.            
        
for num, line in enumerate(members_ano_1, 0):
    if line.startswith("<ordinary_members>"):
        start_om = num
    if line == "</ordinary_members>":
        end_om = num +1

for num, line in enumerate(members_ano_1, 0):
    if line.startswith("<corresponding_members>"):
        start_cm = num
    if line == "</corresponding_members>":
        end_cm = num +1        

#members_ano_1[start_om:end_om]

In [104]:
members_ano_2 = []

for num, line in enumerate(members_ano_1, 0):
    
    if num in range(start_om, end_om):                                 #I only go through the range of the ordinary members section.

        con_mem = fuzz.ratio("a) Beständige Mitglieder. ", line)
        in_mem = fuzz.ratio("b) in oder nahe bei Riga lebende Mitglieder. \n", line)        #"1) In oder bei Riga wohnhaft. \n"
        out_mem = fuzz.ratio("c. Auswärtige Mitglieder. \n", line)                     #2) Ausserhalb Riga's wohnhaft. \n
        fem_mem = fuzz.ratio("IV.Teilnehmerinnen \n", line)
        mal_mem = fuzz.ratio("V. Teilnehmer \n", line)
        
        if con_mem >= 80:
            members_ano_2.append(f"<constant_members> {line}")                         #I open ordinary members section
            print("OM ConM detected") 
            
        elif in_mem >= 80:
            members_ano_2.append("</constant_members>")
            members_ano_2.append(f"<in_hometown> {line}")                 #I open the in hometown section
            print("OM In detected")

        elif out_mem >= 80:
            members_ano_2.append("</in_hometown>")                        #I close the in hometown section 
            members_ano_2.append(f"<outside_hometown> {line}")
            print("OM Out detected")
        
        elif fem_mem >= 80:
            members_ano_2.append("</outside_hometown>")                        #I close the in hometown section 
            members_ano_2.append(f"<female_participants> {line}")
            print("OM Fem detected")
            
        #elif mal_mem >= 80:
            #members_ano_2.append("</female_participants>")
            #members_ano_2.append("</outside_hometown>")                        #I close the in hometown section 
            #members_ano_2.append(f"<male_participants> {line}")
            #print("OM Mal detected")

        elif line == "</ordinary_members>":     
            #members_ano_2.append("</outside_hometown>")                              #I close the outside hometown section
            members_ano_2.append("</female_participants>")
            #members_ano_2.append("</male_participants>")
            members_ano_2.append(line)
            print("OM tag detected")
            
        else:
            members_ano_2.append(line)
    
    else:
        members_ano_2.append(line)                                       #Don't forget to also append the lines outside of the sections.

members_ano_2


OM ConM detected
OM In detected
OM Fem detected
OM tag detected


["<section type='list'> Verzeichnis der ülitglieder. \n",
 '<members>',
 '<honorable_members> I. Ehrenmitglieder. \n',
 '. Dr. G. Schweinfurth in Berlin seit (1867) 1872 \n',
 '. G. Schweder, Staatsrat, in Riga, Peter-Paulstrasse 2 „ (1861) 1887 \n',
 '. Dr. 0. Drude, Geh. Hofrat, Professor, in Dresden „ 1895 \n',
 '. Dr. A. Jentzsch, Professor, Geh. Bergrat, in Berlin „ 1895 \n',
 '. Dr. E. Mach, Professor, in Wien „ 1895 \n',
 '. Dr. A. v. Oettingen, Wirkl. Staatsrat, Professor, in Leipzig ... „ (1870) 1895 \n',
 '. Dr. W. Ostwald, Geheimrat, Professor, in Leipzig „ 1895 \n',
 '. Dr. L. Stieda, Geh. Medizinalrat, Professor, in Königsberg . . „ (1870) 1895 \n',
 '. Dr. A. Wojeikow, Wirkl. Staatsrat, Professor, in St. Petersburg . „ 1895 \n',
 '. M. Rykatschew, Gen.-Maj., Dir. d. Nikolai-Obs., in St. Petersburg „ 1899 \n',
 '. A. Werner, Oberlehrer, Dir. d. meteorol. Stat., Riga, Gertrudstrasse 35 „ (1876) 1902 \n',
 '. Dr. J. Borodin, Geheimrat, Akademiker, in St. Petersburg ... „ (19

In [105]:
#Same as GEG
#First step of the cleaning process of the membership list
#Adjust Ano numbers in case third level structure was skipped

members_ano_3 = []

for line in members_ano_2:
    if line.startswith("— "):                      #I remove the page number markers 
        members_ano_2.remove(line)

for line in members_ano_2:
    new_line = re.sub("\n", "", line)             #I remove the line breaks to reconnect information about one person that is split in two lines.
    members_ano_3.append(new_line)

        
members_ano_3

["<section type='list'> Verzeichnis der ülitglieder. ",
 '<members>',
 '<honorable_members> I. Ehrenmitglieder. ',
 '. Dr. G. Schweinfurth in Berlin seit (1867) 1872 ',
 '. G. Schweder, Staatsrat, in Riga, Peter-Paulstrasse 2 „ (1861) 1887 ',
 '. Dr. 0. Drude, Geh. Hofrat, Professor, in Dresden „ 1895 ',
 '. Dr. A. Jentzsch, Professor, Geh. Bergrat, in Berlin „ 1895 ',
 '. Dr. E. Mach, Professor, in Wien „ 1895 ',
 '. Dr. A. v. Oettingen, Wirkl. Staatsrat, Professor, in Leipzig ... „ (1870) 1895 ',
 '. Dr. W. Ostwald, Geheimrat, Professor, in Leipzig „ 1895 ',
 '. Dr. L. Stieda, Geh. Medizinalrat, Professor, in Königsberg . . „ (1870) 1895 ',
 '. Dr. A. Wojeikow, Wirkl. Staatsrat, Professor, in St. Petersburg . „ 1895 ',
 '. M. Rykatschew, Gen.-Maj., Dir. d. Nikolai-Obs., in St. Petersburg „ 1899 ',
 '. A. Werner, Oberlehrer, Dir. d. meteorol. Stat., Riga, Gertrudstrasse 35 „ (1876) 1902 ',
 '. Dr. J. Borodin, Geheimrat, Akademiker, in St. Petersburg ... „ (1901) 1910 ',
 '. W. Peterse

In [106]:
#Same as GEG
#Second step of the cleaning process of the membership list
#NB! This is only possible if all members have a clear marker at the beginning --> Some files have OCR errors here. 

members_ano_4 = []

for line in members_ano_3:
    if line.startswith("<"):
        new_line = re.sub(r"<", r"\n<", line)                 #I insert a line break before each marker
        members_ano_4.append(new_line)
    else:
        new_line = re.sub(r"^(\S{1,3})\.", r"\n\1)", line, 1)      #I insert a number before each number signifying a person ( I remove the ^ denoting the beginning of the line only for members list 1921.
        members_ano_4.append(new_line)                             #I should have remembered to reinsert the ^ again for these a lot of manual changes until 1895 would not have been necessary...
        
members_ano_4

["\n<section type='list'> Verzeichnis der ülitglieder. ",
 '\n<members>',
 '\n<honorable_members> I. Ehrenmitglieder. ',
 '. Dr. G. Schweinfurth in Berlin seit (1867) 1872 ',
 '. G. Schweder, Staatsrat, in Riga, Peter-Paulstrasse 2 „ (1861) 1887 ',
 '. Dr. 0. Drude, Geh. Hofrat, Professor, in Dresden „ 1895 ',
 '. Dr. A. Jentzsch, Professor, Geh. Bergrat, in Berlin „ 1895 ',
 '. Dr. E. Mach, Professor, in Wien „ 1895 ',
 '. Dr. A. v. Oettingen, Wirkl. Staatsrat, Professor, in Leipzig ... „ (1870) 1895 ',
 '. Dr. W. Ostwald, Geheimrat, Professor, in Leipzig „ 1895 ',
 '. Dr. L. Stieda, Geh. Medizinalrat, Professor, in Königsberg . . „ (1870) 1895 ',
 '. Dr. A. Wojeikow, Wirkl. Staatsrat, Professor, in St. Petersburg . „ 1895 ',
 '. M. Rykatschew, Gen.-Maj., Dir. d. Nikolai-Obs., in St. Petersburg „ 1899 ',
 '. A. Werner, Oberlehrer, Dir. d. meteorol. Stat., Riga, Gertrudstrasse 35 „ (1876) 1902 ',
 '. Dr. J. Borodin, Geheimrat, Akademiker, in St. Petersburg ... „ (1901) 1910 ',
 '. W. P

In [107]:
out_filename = f'Output/NVR/{year}_NVR_Members_Ano.txt'                

filepath = Path(out_filename)                             
filepath.parent.mkdir(parents=True, exist_ok=True)                  #creates the folders if they don't exist yet

with open(out_filename, 'x') as fp:
    fp.write("".join(str(item) for item in members_ano_4))          #By joining the list elements without any symbol the 
                                                                    #line breaks will be at the end of each line the next time I read the document in 

##### Manual changes:
I always make sure that the start numbers and diplom numbers are formated correctly!

- In file 1872_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1872_NVR_Members_Ano.txt I manually adjust persons with only their diplom number instead of a start number. They are all marked with "00)" in the beginning. Those are the ones that were admitted to the society between 14th of June 1870 and 1st March 1871.
- NB: In file 1872_NVR_Members_Ano.txt are some grave OCR errors or rather elipses, but the missing members can be identified based on their diplom number. 
- In file 1874_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1874_NVR_Members_Ano.txt I manually adjust persons with only their diplom number instead of a start number. They are all marked with "00)" in the beginning. Those are the ones that were admitted to the society since the last membership list was published. 
- In file 1874_NVR_Members_Ano.txt I manually remove the last two sentences stemming from the end of the volume. 
- In file 1877_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1877_NVR_Members_Ano.txt I manually remove the last two sentences stemming from the end of the volume.
- In file 1880_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1881_NVR_Ano.txt I manually add a line break in line 2553 after "A. Ehrenmitglieder. "
- In file 1881_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1882_NVR_Ano.txt I manually remove a "\n" from the closing section tag for the membership list in line 2379 and in line 2086. 
- In file 1882_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1883_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1883_NVR_Members_Ano.txt I manually remove the last two sentences that don't belong to the membership list. 
- In file 1885_NVR_Ano.txt I manually add "\</section>" and "\<section type='report'>" to line 2042f to clearly mark the end of the membership list. 
- In file 1885_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1887_NVR_Ano.txt I manually add "\</section>" and "\<section type='report'>" to line 2287f to clearly mark the end of the membership list. 
- In file 1887_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1887_NVR_Ano.txt I manually add "\</section>" and "\<section type='text'>" to line 2548f to clearly mark the end of the membership list. 
- In file 1889_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1891_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1891_NVR_Members_Ano.txt I manually remove the last two sentences that don't belong to the membership list.
- In file 1893_NVR_Ano.txt I manually remove a "\n" from the closing section tag for the membership list in line 595.
- In file 1893_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1897_NVR_Members_Ano.txt I manually correct falsely formated start numbers. Quite a lot to add individually. No longer diplom numbers or in/out hometown. 
- In file 1899_NVR_Ano.txt I manually add "\</section>" and "\<section type='report'>" to line 9255f to clearly mark the end of the membership list. 
- In file 1889_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1901_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1901_NVR_Members_Ano.txt I manually remove the last two sentences that don't belong to the membership list.
- In file 1902_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1902_NVR_Members_Ano.txt I manually remove the last two sentences that don't belong to the membership list.
- In file 1903_NVR_Members_Ano.txt I manually correct falsely formated start numbers. Quite a lot to adjust individually.
- In file 1903_NVR_Members_Ano.txt I manually remove the last two sentences that don't belong to the membership list.
- In file 1904_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1904_NVR_Members_Ano.txt I manually remove the last two sentences that don't belong to the membership list.
- In file 1906_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1906_NVR_Members_Ano.txt I manually remove the last two sentences that don't belong to the membership list.
- In file 1908_NVR_Members_Ano.txt I manually correct falsely formated start numbers. Frist year with female members! 
- In file 1908_NVR_Members_Ano.txt I manually remove the last two sentences that don't belong to the membership list.
- In file 1909_NVR_Ano.txt I manually add "\</section>" and "\<section type='text'>" to line 10089f to clearly mark the end of the membership list.
- In file 1909_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1910_NVR_Members_Ano.txt I manually correct falsely formated start numbers. Quite a lot to add individually.
- In file 1910_NVR_Members_Ano.txt I manually remove the last two sentences that don't belong to the membership list. 
- In file 1911_NVR_Ano.txt I manually add "\</section>" and "\<section type='report'>" to line 4016f to clearly mark the end of the membership list.
- In file 1911_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
- In file 1912_NVR_Ano.txt I manually add "\</section>" and "\<section type='text'>" to line 5659f to clearly mark the end of the membership list.
- In file 1912_NVR_Members_Ano.txt I manually correct falsely formated start numbers.
